### ISSUE TITLE
poor syntax highlighting

### ISSUE THREAD

**Issue by daverous** [krvajal/vscode-fortran-support#1]
Syntax highlighting is incomplete. E.g. **call** is not highlighted. Neither is **program**. This would be very useful to add.

**Comment by krvajal** [comment]
I was quite busy these days but now I a catching back.
Below you can find an image where *program* and *call* are both highlighted properly.
![syntax](https://user-images.githubusercontent.com/5899385/27802502-82a1d2f2-5ffa-11e7-8d86-f533fba22ccf.png)

**Comment by krvajal** [comment]
Fixed
