### ISSUE TITLE
more snippets

### ISSUE THREAD

**Issue by PaulXiCao** [krvajal/vscode-fortran-support#104]
a snippet for if-else blocks would be nice.
maybe even another one for the one-line version?

UPDATE
why not add alot more snippets? i found snippets in the atom/fortran package: 
https://github.com/dparkins/language-fortran/blob/master/snippets/language-fortran.cson

**Comment by krvajal** [comment]
I am fine with adding more snippets but I don't have the time to do it myself. PRs are welcome though

**Comment by pedro-ricardo** [comment]
Done in #123
