### ISSUE TITLE
Snippets uppercase/lowercase settings

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#111]
Uppercase/Lowercase setting does not apply to Snippets, as seen below by the snippet  `program` 

![](https://user-images.githubusercontent.com/15893711/51418243-821d8700-1b69-11e9-8ca9-c35783d5cf8d.png) ![](https://user-images.githubusercontent.com/15893711/51418230-6f0ab700-1b69-11e9-8309-66129ec12c8b.png)

**Comment by JHenneberg** [comment]
In addition or as previous step it would be usefull to have first keywords like INTEGER, SUBROUTINE etc defined.

For now I have to create snippets for keywords which are uppercase which works fine but is just not that elegant :).

**Comment by machsix** [comment]
any update on this? Even if I set the case to uppercase and type `PRO` the intellisense provides `program`

**Comment by gnikit** [comment]
The snippet casing is a limitation of how snippets are implemented in VSCode. As far as I can tell there is no easy, elegant way to fix this.
Even if we used TextMate files for our snippets this would still occur, not to mention the challenge of implementing snippets in TextMate format.

The only easy solution that can be added in the extension is what @JHenneberg has done, copies of all snippets for lower and upper case and then it would be up to the user to pick the right prefix. 

I suspect there might be a way to use TypeScript and avoid code duplication for snippets generation (I think the C++ extension does it) but that would require a lot of work for something that is purely for aesthetics and has trivial solutions.
For the end user the solutions are:
- Create user defined snippets with  uppercase, 
- use a formatter  and enforce formatting rules there or 
- simply call from VSCode `Transform to Uppercase`, `lowercase`, `snakecase`, etc. on your document/selection.

I do not think that it is in the books for this to be addressed anytime soon, so I am closing the issue. 
However, PRs are more than welcome.
