### ISSUE TITLE
Autocompleting "else" to "erfc_scaled"

### ISSUE THREAD

**Issue by jacobwilliams** [krvajal/vscode-fortran-support#113]
When I type "else" and press Return, it always turns into "erfc_scaled". Any way to get it to recognize "else" as a keyword?

**Comment by pedro-ricardo** [comment]
I know it's not the answer you're looking for but, similar errors  happened to me as well, to "correct" that i configure VSCode do accept suggestions on Tab instead of Return.
I'm currently busy to do it, but yes, there is a way to add it in the extension as a keyword.

**Comment by pedro-ricardo** [comment]
@jacobwilliams Seen another one in the mean time? Besides `else` I've also added 'stop' because it was completing as `set_exponent`.
