### ISSUE TITLE
Lower case in Fortran language server promt

### ISSUE THREAD

**Issue by newmrdenis** [krvajal/vscode-fortran-support#114]
I am using the additional feature of the extension which is Fortran Language server. The problem with it is I could not find any way to change the case of results as described in its repo. They say it can be achieved in two ways by the key when launching and by the project specified config file. But they both as I see are unavailable over the extension. Maybe one more setting point or connect it with a preferable case (existing point)?

**Comment by pedro-ricardo** [comment]
@newmrdenis Maybe i didn't understand the question but, the [Fortran Language Server](https://github.com/hansec/fortran-language-server) and its extension to VSCode ([FORTRAN IntelliSense](https://github.com/hansec/vscode-fortran-ls)) aren't a feature of this extension. 
This extension here simply highlight and lint.
For questions, bugs and other issues please visit their repos, Links above.

**Comment by newmrdenis** [comment]
@pedro-ricardo I am sorry but I got this info from the **readme** to **this repo** [https://github.com/krvajal/vscode-fortran-support#fortran-language-server-experimental](url). And my discussion on the settings is based on [https://github.com/hansec/fortran-language-server#language-server-settings](url) that is "--lowercase_intrinsics". Am I mistaken?

**Comment by pedro-ricardo** [comment]
Oh i see... That's an **experimental** feature, I don't use it and I'm also not sure if it works... 
Therefore I recommend you to use that feature only if you intend to contribute to the development of it.

That said, to get [Fortran Language Server](https://github.com/hansec/fortran-language-server) to work in VSCode I recommend you to leave our option `false` and install the  [FORTRAN IntelliSense](https://github.com/hansec/vscode-fortran-ls) extension, which I heard that does a better job in handling the **Fortran Language Server**.
Then maybe you can find the configuration `--lowercase_intrinsics` in there.

Maybe I didn't understood you question once again =] (that happens). Let me know if that's the case.

**Comment by pedro-ricardo** [comment]
@newmrdenis  Can i close this?

**Comment by newmrdenis** [comment]
@pedro-ricardo Yes, sure. Thanks for clarification.
