### ISSUE TITLE
fortran-language-server not recognized

### ISSUE THREAD

**Issue by PaulXiCao** [krvajal/vscode-fortran-support#119]
I get the following error message after opening up vs code
```
[Error - 12:07:18 PM] Starting client failed
Error: Unsupported server configuration {
    "command": null,
    "args": [],
    "options": {}
}
	at createMessageTransports._getServerWorkingDir.then.serverWorkingDir (<$HOME>/.vscode/extensions/krvajalm.linter-gfortran-2.0.2/node_modules/vscode-languageclient/lib/main.js:363:35)
```
It just started maybe a couple weeks ago.

I enabled the option: language server
```
...
    "fortran.useLanguageServer": true,
...
```

The fortran language server is installed w/ the latest version
```
$ fortls --version
1.5.0
```
It is installed in the following path (included in $PATH)
```
$ which fortls
<$HOME>/.local/bin/fortls
$ echo $PATH
...:<$HOME>/.local/bin:...
```

any ideas?

**Comment by pedro-ricardo** [comment]
Hello there,
That's an **experimental** feature, I don't use it and I'm also not sure if it works...
Therefore I recommend you to use that feature only if you intend to contribute to the development of it.

That said, to get **Fortran Language Server** to work in **VSCode** I recommend you to leave our option `false` and install the [FORTRAN IntelliSense](https://marketplace.visualstudio.com/items?itemName=hansec.fortran-ls) extension, which I heard that does a better job in handling the Fortran Language Server.

**Comment by PaulXiCao** [comment]
Thanks @pedro-ricardo . Your work around worked (disabling the fortran language server option and installing FORTRAN IntelliSense).
