### ISSUE TITLE
Compiler options highlight seems wrong

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#12]
When using compilation statements `#ifdef`, `#if defined()`, `#else` and `#endif` the code highlight the line with two different colors.
In the figure below the whole line should be **blue**, or some other color:
![highlight](https://user-images.githubusercontent.com/15893711/33687388-380d5514-dabf-11e7-81b8-9e6795fd1203.png)

**Comment by krvajal** [comment]
I have checked other languages that support preprocessing and it seems like it is pretty standard to have them highlighted this way.
