### ISSUE TITLE
problem with fortran.includePaths

### ISSUE THREAD

**Issue by wdaniau** [krvajal/vscode-fortran-support#124]
Hello,
Thanks for providing this extension.

I have a problem under linux with fortran.includePaths, if I specify only one value in the array, it works well, but with 2 values it doesn't. 
By spying the generated gfortran command line it appears that the generated include paths are as follows : 

``-I /path1 /path2``

instead of

``-I/path1 -I/path2``

By modifying helper.js line 78 : 
```javascript
return '-I ' + paths.join(' ');
```
into 
```javascript
return '-I' + paths.join(' -I');
```
then it works well.

**Comment by pedro-ricardo** [comment]
Hello there, thank you for pointing that out.
Can you create a Pull Request for this since you've already fixed it?

Thank you! :+1:

**Comment by wdaniau** [comment]
Done.

**Comment by wdaniau** [comment]
This first solution I gave did not work well, it only worked under my testing setup.
I updated the branch for which I created the pull request with a solution using a string array that actually works at least under linux.
