### ISSUE TITLE
Some Intrinsic functions are missing

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#13]
The `allocatable` declaration statement isn't highlighted, as well as some Intrinsic functions like `dsqrt` and `move_alloc`. Logical statements like `.and.` , `.or.`, `>=` and `==` are missing too. More examples in the figure below:
![highlight3](https://user-images.githubusercontent.com/15893711/33709564-dcdf7f6c-db24-11e7-9c61-c7effa6a1244.png)

If adding this keywords is as simple as adding names to a file, tell me the file i have to look at and i can do it if you want.

**Comment by krvajal** [comment]
The syntax highlighting is provided by this [file](https://github.com/krvajal/vscode-fortran-support/blob/master/syntaxes/fortran90.tmLanguage) and it uses the TexMate syntax. It should be easy to add.
Regarding the logical operators, it seems to me they are already added here https://github.com/krvajal/vscode-fortran-support/blob/master/syntaxes/fortran.tmLanguage#L227
but have to double check

**Comment by krvajal** [comment]
@pedro-ricardo what file extension are u using?

**Comment by pedro-ricardo** [comment]
Thank you for the quick reply, i'll take a look. It will take some time because I don't know how to compile and test yet, but i'll learn eventually.

**Comment by pedro-ricardo** [comment]
About the logical operators, the name `keyword.operator(...)` does not have a color associated to it. So i just changed that key to `keyword.logical(...)` for example, and it highlights correctly. 
I'm adding the missing intrinsic functions, and will commit as soon as i resolve the conflict  between the `storage.modifier.fortran.modern` keywords and the operator `::`.

**Comment by pedro-ricardo** [comment]
Still can't find that weird conflict ... Here is when it happens, maybe you can help me out with some directions
**Sample:**
![highlight3](https://user-images.githubusercontent.com/15893711/33907937-f6e557b8-df6d-11e7-8a42-9c3443015389.png)

**Code:**
```
program test2 
    !test2.f90
    implicit none
    
    ! In this case the 'allocatable' and 'target' statements aren't highlighted
    double precision, allocatable, target, dimension(:):: d
    
    ! But in this case they are !
    type(solid), allocatable, target, dimension(:):: dr
    
end program test2
```

**Comment by krvajal** [comment]
Hi, this week I am extremely busy but for sure I will take a look at it
first thing next week :) . Sorry I can help just right now.

*Lic. Miguel Carvajal*
*Condensed Matter Theory Group*
*Bariloche Atomic Center*
*CNEA*

**Comment by krvajal** [comment]
@pedro-ricardo I have been looking into the issue and I found a pattern for the bug
```
! not highlighted
double precision, allocatable, target, dimension(:):: d
! highlighted
double, allocatable, target, dimension(:):: d
```    
So the problem is with the precision keyword.
I am pushing some changes that fix the problem but adding the definitions to the base file. This is not a good solution do.
Will try to get a bit deeper in the TM syntax and push a better fix later on.
