### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by sindizzy** [krvajal/vscode-fortran-support#131]
Great extension! I just started using it and I love it.
If I wanted to change some colors for keywords would it be possible with the extension installed or would I have to compile my own fork?

Thanks

**Comment by pedro-ricardo** [comment]
Hello there,
Besides changing the whole color scheme of VSCode, the colors are controlled by the scopes in `tmlanguage` files.

With the scope in `tmlanguage` file, VSCode define the color based on the selected color scheme. There isn't a place in the extension that has explicitly defined green or yellow to something. 
(But maybe I just didn't understood it =] )

As they are json files, you can modify them at the installation folder of your extension, **but be aware** that if you do it this way, **you'll loose your setting when we launch a new version**.

Therefore, I believe that the best way is for you to fork and install it.

**Comment by sindizzy** [comment]
Ah ok. Thanks for the info.

**Comment by pedro-ricardo** [comment]
@sindizzy can you close this?

**Comment by sindizzy** [comment]
done
