### ISSUE TITLE
Show the current program/subroutine/function

### ISSUE THREAD

**Issue by K1-ZR** [krvajal/vscode-fortran-support#134]
A feature that shows the current program/subroutine/function where the cursor is, would be helpful. [Scope Bar](https://marketplace.visualstudio.com/items?itemName=amos402.scope-bar) is an extension with similar functionalities, although it is not working for FORTRAN. Would it be a better idea if you/I ask them to support FORTRAN in Scope Bar extension?

**Comment by pedro-ricardo** [comment]
Hello there...
As far as I see in an example here:
![Screenshot_20190608_182437](https://user-images.githubusercontent.com/15893711/59152455-b7444c00-8a1a-11e9-9b88-6eed810a289d.png)

It does work ... The Scope Bat identify current function as `func2`

Our Extension does not use `program` and `module` as symbols so they will never appear on the Scope Bar, but subroutine and function will be there.

**Comment by pedro-ricardo** [comment]
@K1-ZR Can I close this?

**Comment by GNikit** [comment]
By the way what you are asking can already be accomplished (in a way at least) by using the extensions Modern Fortran (this one) + [FORTRAN IntelliSense](https://github.com/hansec/vscode-fortran-ls) and enabling breadcrumbs in by

``` json
"breadcrumbs.enabled": true,
``` 

This produces the following result, I expanded the breadcrumb trail for demonstration purposes

![image](https://user-images.githubusercontent.com/16143716/75497546-79c68b00-59bc-11ea-9e02-9b217cb9542e.png)

**Comment by pedro-ricardo** [comment]
As I said before, the scope bar extension along with this one does the trick. The current scope appears in the blue bar of my previous screenshot.

> By the way what you are asking can already be accomplished  (in a way at least)
