### ISSUE TITLE
Select case at left margin

### ISSUE THREAD

**Issue by sujona** [krvajal/vscode-fortran-support#136]
The `select case` statement jumps to the left margin (zero indentation) regardless of context.

**Comment by pedro-ricardo** [comment]
Hello there! Thank you for the report .. I'll look into it, this seems simple.
The problem happens when typing the word `case` of `select case`, meaning that the rule can't differentiate the `case` statement indentation rule from the `select case` one.

**Comment by pedro-ricardo** [comment]
Ok ... Found it, that was a missing parenthesis.
Fixed in #138

**Comment by sujona** [comment]
Good stuff! :)
