### ISSUE TITLE
openMP line continuation 

### ISSUE THREAD

**Issue by sujona** [krvajal/vscode-fortran-support#139]
Hi Pedro! Line continuations in openMP statements get incorrect highlighting. For example
```
    !$omp parallel do default(none) &
    !$omp private(a,bunch,of,variables) &
    !$omp shared(more,vari,ables)
    do
    enddo
    !$omp end parallel do
```

**Comment by pedro-ricardo** [comment]
Hello there @sujona, I don't have experience with other editors and `$omp` directives... So how this should be highlighted?

![Screenshot_20190618_193608](https://user-images.githubusercontent.com/15893711/59724492-6a255e80-9200-11e9-9ea2-f4268a8e013d.png)

The wrong thing is that the `private` keyword should be highlighted just like `parallel do default`?

**Comment by sujona** [comment]
When the line is not broken it looks like 
![code_omp](https://user-images.githubusercontent.com/19970804/59775236-22aadb00-92b1-11e9-885a-375914af8bec.png)
Which I think is fine, so if the "&":s are white and the "!$omp":s are green like in the first line of your screenshot, and the colors of the "private(var1,...)" and "shared(var2,...)" are as in the single-line case in my screenshot, that would make sense I think.

**Comment by pedro-ricardo** [comment]
@sujona Is something like this ok?
![Screenshot_20190627_105718](https://user-images.githubusercontent.com/15893711/60272362-62358080-98ca-11e9-92a7-ce3a92a80c60.png)

**Comment by pedro-ricardo** [comment]
I don't have any large code with an example of `!$omp` to check if my modification will affect wrongly the highlight of some other OpenMP directive... do you?

If you do, i can tell you how to apply this change in your extension so you can check other directives in your code for inconsistencies.

**Comment by sujona** [comment]
Yeah, it works great! Maybe you should add instructions in the readme on how to install it manually. I uninstalled the official plugin, cloned this repo, checked out the `hotfix/highlight` branch and linked it into `.vscode/extensions/ with `ln -s`.

**Comment by pedro-ricardo** [comment]
There is no need for that. This fix will join the new release soon.
