### ISSUE TITLE
How to disable the linter?

### ISSUE THREAD

**Issue by andreypudov** [krvajal/vscode-fortran-support#14]
I am using Intel Fortran compiler because of error messages coming from the extension I would like to disable linter. Could you please to help with required settings?

**Comment by zolamusic** [comment]
Add `"fortran.linterEnabled": false` in your setting.

**Comment by krvajal** [comment]
@andreypudov did you success in disabling the linter? Let me know so I can close this.

**Comment by krvajal** [comment]
I am closing this as it seems to be solved
