### ISSUE TITLE
Incorrect symbol kind of module subroutines

### ISSUE THREAD

**Issue by letmaik** [krvajal/vscode-fortran-support#140]
The symbol kind shown for subroutines in modules should be "function" but currently is "method".  "method" is reserved for usage in classes. In the context of Fortran, "method" should only be used for type-bound procedures (see bottom of http://fortranwiki.org/fortran/show/Object-oriented+programming).

**Comment by pedro-ricardo** [comment]
Can you illustrate what is that you think is wrong ?
Not sure if you are complaining about the highlight or the outline ?

**Comment by letmaik** [comment]
The outline yeah, when you hover over an entry which is a subroutine then it says "method" but should be "function".

**Comment by pedro-ricardo** [comment]
I get it ...
But in Fortran it's useful to separate `function` and `subroutine` their calling syntax is too different, ideally those icons should be also different ... I know that the `method` label is wrong but inserting all into `function` just seem wrong as well.

I look at it some time ago, but due to the lack of options to differ `function` and `subroutine` it stayed as it is.

So... I agree with you that `method` is wrong, but It also disagree that it should be `function`.
Any Ideas?

**Comment by pedro-ricardo** [comment]
Also note that `method` is a C word ... 
To Fortran `functions` and `subroutines` are both called **procedures** and when associated to object-programming they are called **type-bound procedures**

### Below are the current options we have to set symbols:
Different line means different icon

  |  Symbol Options
-- | --
  | Methods, Functions and Constructors
  | Variables and Fields
  | Classes
  | Interfaces
  | Modules
  | Properties and Attributes
  | Values and Enumerations
  | References
  | Keywords
  | Global Identifiers
  | Colors
  | Unit
  | Snippet Prefixes
  | Words
  | Miscellaneous

**Comment by letmaik** [comment]
I agree there is a semantic mismatch with Fortran, but I would still make the distinction of using `method` to refer to a procedure that's associated with an object (in Fortran type-bound procedure) whereas `function` does not have that association.
I see your point of having separate icons and that this may be a more practical compromise. I guess it just bothers me that the semantics are more wrong in this case.

**Comment by letmaik** [comment]
By the way, here is the feature request for adding `procedure` as symbol kind: https://github.com/microsoft/language-server-protocol/issues/344#issuecomment-452357135. Not sure it will ever happen though.

**Comment by pedro-ricardo** [comment]
You have a point...
In practice this distinction doesn't even happen because the icon is still the same.

I guess that while there is no better option. This is a valid fix.

**Comment by pedro-ricardo** [comment]
Will you make a PR for it?

**Comment by letmaik** [comment]
Sure, shouldn't be hard.

**Comment by pedro-ricardo** [comment]
Thanks ... Remember that I'm not the owner, so your PR description need to have some explanation

**Comment by pedro-ricardo** [comment]
That was fast!

**Comment by letmaik** [comment]
Ah, I didn't realize, will add more detail.
