### ISSUE TITLE
Fortran syntax error checking is not working in VS code Remote Developement

### ISSUE THREAD

**Issue by subratappt** [krvajal/vscode-fortran-support#145]
VSCode Version: 1.36.1
    Modern Fortran Version: 2.1.1
    Local OS Version: macOS 10.13.6
    Remote OS Version: CentOS Linux release 7.6.1810 (Core)
    Remote Extension/Connection Type: SSH/Docker/WSL

I am using Modern Fortran extension in VS code for the syntax highlighting and error checking. It is working fine locally but syntax error checking is not working in Remote Development. I have installed the extension in both the local machine and remote server. Both the machines have `gfortran` installed, and I have provided the `gfortran` path in the `settings.json`.

Does this issue occur when you try this locally?: No

**Comment by gnikit** [comment]
I often use remote SSH to write/edit code and I haven't experienced anything like this. 
Could you add the `gfortran` path to your `PATH` variable and try again?
Also, could you provide your settings for Modern Fortran?

**Comment by gnikit** [comment]
I will be closing this issue now, feel free to reopen if the problem persists.
