### ISSUE TITLE
How do you use linting?

### ISSUE THREAD

**Issue by LukeIreland1** [krvajal/vscode-fortran-support#147]
I've manually enabled linting in the settings, but I can't seem to find where the linting reports/info are presented.

**Comment by pedro-ricardo** [comment]
**linter** shows informations in pop-ups through the code and in the problems tab.
Usually just enabling it is enough.
Refer to this comment:
https://github.com/krvajal/vscode-fortran-support/issues/159#issuecomment-592954220
for further derails on compilation options 

If it doesn't help , please detail your settings, vscode version, and operating system.
