### ISSUE TITLE
"select" in variable name confuses parser

### ISSUE THREAD

**Issue by kc9jud** [krvajal/vscode-fortran-support#149]
Opening a file which contains a variable with `select` in the name appears to crash/confuse the parser:

![image](https://user-images.githubusercontent.com/4133644/65474897-895d0900-de4b-11e9-9ef1-ca0d4385b3f9.png)

with variable commented out:
![image](https://user-images.githubusercontent.com/4133644/65474926-9e399c80-de4b-11e9-9d31-91c6d43993f3.png)

**Comment by danlub** [comment]
Same thing happens to me. Came here to report the same issue

**Comment by pedro-ricardo** [comment]
That's my bad :-1:  ... I made a change when trying to generalize the `select case` and `select type` keywords that can be the cause of it ... I'll try to solve it soon.
Thank you for your feedback

**Comment by kc9jud** [comment]
@pedro-ricardo Any updates?

**Comment by pedro-ricardo** [comment]
I'm sorry @kc9jud , but my job is currently consuming all the time I've got. So I still haven't look into this, and to be honest it's way down on my priorities.

**Comment by kc9jud** [comment]
No worries -- I was considering trying to come up with a PR, but I wanted to make sure you weren't already working on it.
