### ISSUE TITLE
Highlighting Fortran name list files

### ISSUE THREAD

**Issue by MuellerSeb** [krvajal/vscode-fortran-support#153]
Hey there,

I'd like to highlight fortran name lists in VS-code, but I can't find an option to do so? In my case the file extension is ".nml". Maybe I am missing something and just need a hint.

Cheers,
Sebastian

**Comment by danlub** [comment]
Hi, Sebastian
I wanted to do the same, so the workaround that I did is to add the namelist extension (in my case ".inp") as a file associated with fortran. The highlighting works relatively well

To do so, you can add this snippet to your settings.json
```json
    "files.associations": {
        "*.nml": "FortranFreeForm"
    }
```

**Comment by MuellerSeb** [comment]
@danlub cool! That did the trick. Thanks

**Comment by pedro-ricardo** [comment]
This can be closed @MuellerSeb? Since there is a way to do it in VSCode Settings

**Comment by MuellerSeb** [comment]
Of course. Thanks!
