### ISSUE TITLE
add vertical rule

### ISSUE THREAD

**Issue by zhyiyu** [krvajal/vscode-fortran-support#156]
Thanks for this amazing Fortran support for VS code! It would be perfect if vertical rules could be added to the files.

For example, in Fortran 77 code, column is for comment indicator, column 2 to 5 are for statement labels, column 6 is for continuation of previous line, and columns beyond 80 are ignored.

For Fortran 90, there is just a line length limit need to be indicated.

Thanks!

**Comment by zhyiyu** [comment]
Also, I was trying to add vertical rules by hand with

```
{
    "[fortran]":
    {
        "editor.rulers": [0, 1, 5, 6, 79, 120]
    },
}
```

but it would not work. The reason I know this is that extension [Fortran](https://marketplace.visualstudio.com/items?itemName=Gimly81.fortran) would work.

**Comment by gnikit** [comment]
As you correctly mentioned the way of doing this is to set language specific rulers in your `settings.json`. Your only mistake is that you are using the language ID `fortran` which is not from our extension. To enable multiple rulers only for fixed format fortran you would need to add this in you settings.

```json
    "[fortran_fixed-form]": {
        "editor.rulers": [0, 1, 5, 6, 79, 120]
    },
```

##
NOTE: We will soon be changing the language ID `fortran_fixed-form` to `FortranFixedForm` next release probably.

I will now be closing this issue, feel free to reopen if you have a problem.
