### ISSUE TITLE
.mod files for linting out of src directory

### ISSUE THREAD

**Issue by newmrdenis** [krvajal/vscode-fortran-support#159]
Hello there. First of all thank you a lot for creating and maintaining this great extension!
 
My question is pretty simple: is there any way to create .mod files needed for linting in user-specific directory? Because my project has the corresponding structure:
project
-src
-obj
makefile
And I really want to have the setting specifying the obj dir as storing .mods files. Something like adding -J obj seems not to work.

Thank you for reply in advance.

**Comment by pedro-ricardo** [comment]
Hello there,
Isn't this done with the setting `fortran.includePaths` ? 
Or you want something like #132 ?

**Comment by pedro-ricardo** [comment]
I've tested the include and  `-J` and it works as expected, but the path needs to be absolute

**Comment by pedro-ricardo** [comment]
@newmrdenis  Need any help with this? It worked?

**Comment by newmrdenis** [comment]
Oh, thanks for your reply. I was busy so couldn't answer instantly, sorry.
"Or you want something like #132 ?" No, I don't. As you can see, my work dir structure is pretty simple)

The include works as expected for me, but is it really? You have to paste only absolute path? This really bad. Because I use it for my external libraries and there I specified only an absolute path I've never noticed it .

As for -J option it seems no longer to create .mods file in dir I specified. Or maybe I've done something wrong?

Here I'll try to clarify my request: is there any way to create temporary .mods files, used for checking interfaces of funcs and others, create in the out of dir where the sources of these modules are storing?

**Comment by pedro-ricardo** [comment]
My bad,
I'll make a step-by-step tutorial below to help narrow down the problem your're getting.

**Comment by pedro-ricardo** [comment]
## Intro
Firstly our extension has two major drawbacks (that we are aware of) when it comes to the **linter** usage:

- All folders must be specified as absolute paths
- Sub-folders aren't supported, you need to specify separately every folder

I'm gathering these To-Do developments in #86.

## Tutorial
### Folder structure
This tutorial runs in the following code structure:
```
.
├── bin
│   └── Makefile
├── LICENSE
├── README.md
└── src
    ├── linked_list.f08
    └── test_link.f08
```
Where `linked_list.f08` is the module file and `test_link.f08` the program

Let's compile the code now. Our **linter** helps you see errors end warnings but doesn't know compilation order, linking and stuff like that. After running `make` in the `bin` folder the structure looks like this:
```
.
├── bin
│   ├── a.out
│   ├── linked_list.mod
│   ├── linked_list.o
│   ├── Makefile
│   └── test_link.o
├── LICENSE
├── README.md
└── src
    ├── linked_list.f08
    └── test_link.f08
```
### Include folders
Now we open the **VSCode** in this workspace, with the following settings in this extension:
```jsonc
{
    "fortran.gfortranExecutable": "gfortran",
    "fortran.linterEnabled": true
}
```
By opening the program file (`test_link.f08`) the following error will appear:
![Screenshot_2020-02-29_11-43-54](https://user-images.githubusercontent.com/15893711/75609619-efc81080-5ae8-11ea-9e6b-8eb9de2a9140.png)
The `linked_list.mod` file is in the bin directory so the **linter** can't find it. To solve this we need to add the path to the `bin` folder (where the `linked_list.mod` is). Therefore the settings now become:
```jsonc
{
    "fortran.gfortranExecutable": "gfortran",
    "fortran.linterEnabled": true,
    "fortran.includePaths": [
        "/home/pedro/Documents/Codes/LinkedList/bin"
    ]
}
```
By saving/reopening the `test_link.f08` again and the error will disappear
### Managing temporary `.mod` files
By opening the `linked_list.f08` (the module file) you'll see that a `.mod` file will be created along side `linked_list.f08` file 
![Screenshot_2020-02-29_11-54-02](https://user-images.githubusercontent.com/15893711/75609806-47b34700-5aea-11ea-8a6e-2ba58390d7eb.png)
This means that the **linter** worked and compiled your file, but having the `.mod`files in `src` folder can become a mess. To solve this, let's use the `-J` flag that redirect the `.mod` to `bin`folder where it belongs. This is done in settings like:
```jsonc
{
    "fortran.gfortranExecutable": "gfortran",
    "fortran.linterEnabled": true,
    "fortran.includePaths": [
        "/home/pedro/Documents/Codes/LinkedList/bin"
    ],
    "fortran.linterExtraArgs": [
        "-Wall",
        "-J/home/pedro/Documents/Codes/LinkedList/bin"
    ]
}
```
As you can see, other flags like `-Wall` can be passed the same way.

By excluding that `.mod` created in the `src` folder you can see that by saving/reopening the module file the **linter** will return you errors and warnings but now creating the `.mod` in `bin` dir.

**Comment by pedro-ricardo** [comment]
@newmrdenis I'll wait longer now I promise :+1: 

Let me know if this helps, or if something is still wrong.

**Comment by newmrdenis** [comment]
Yes, now all is clarified.I am really grateful for your spent time. 

P.S. There is one more trouble with -J option such as you have to paste your dir right after -J key. No space is available. This is confusing.

**Comment by pedro-ricardo** [comment]
It doesn't bother me so much since I'm used with similar flags `-I` and `-L` that usually don't have spaces for the folder argument.

But I understand, if it bothers that much you can separate it like this:
```jsonc
"fortran.linterExtraArgs": [
    "-Wall",
    "-J","/home/pedro/Documents/Codes/LinkedList/bin"
]
```
It also works.

I'll leave the closure of this issue to you. If there's something else just ask.

**Comment by newmrdenis** [comment]
Thank you again)

**Comment by Koushikphy** [comment]
> ## Intro
> Firstly our extension has two major drawbacks (that we are aware of) when it comes to the **linter** usage:
> 
> * All folders must be specified as absolute paths
> * Sub-folders aren't supported, you need to specify separately every folder
> 
> I'm gathering these To-Do developments in #86.
> 
> ## Tutorial
> ### Folder structure
> This tutorial runs in the following code structure:
> 
> ```
> .
> ├── bin
> │   └── Makefile
> ├── LICENSE
> ├── README.md
> └── src
>     ├── linked_list.f08
>     └── test_link.f08
> ```
> 
> Where `linked_list.f08` is the module file and `test_link.f08` the program
> 
> Let's compile the code now. Our **linter** helps you see errors end warnings but doesn't know compilation order, linking and stuff like that. After running `make` in the `bin` folder the structure looks like this:
> 
> ```
> .
> ├── bin
> │   ├── a.out
> │   ├── linked_list.mod
> │   ├── linked_list.o
> │   ├── Makefile
> │   └── test_link.o
> ├── LICENSE
> ├── README.md
> └── src
>     ├── linked_list.f08
>     └── test_link.f08
> ```
> 
> ### Include folders
> Now we open the **VSCode** in this workspace, with the following settings in this extension:
> 
> ```js
> {
>     "fortran.gfortranExecutable": "gfortran",
>     "fortran.linterEnabled": true
> }
> ```
> 
> By opening the program file (`test_link.f08`) the following error will appear:
> ![Screenshot_2020-02-29_11-43-54](https://user-images.githubusercontent.com/15893711/75609619-efc81080-5ae8-11ea-9e6b-8eb9de2a9140.png)
> The `linked_list.mod` file is in the bin directory so the **linter** can't find it. To solve this we need to add the path to the `bin` folder (where the `linked_list.mod` is). Therefore the settings now become:
> 
> ```js
> {
>     "fortran.gfortranExecutable": "gfortran",
>     "fortran.linterEnabled": true,
>     "fortran.includePaths": [
>         "/home/pedro/Documents/Codes/LinkedList/bin"
>     ]
> }
> ```
> 
> By saving/reopening the `test_link.f08` again and the error will disappear
> 
> ### Managing temporary `.mod` files
> By opening the `linked_list.f08` (the module file) you'll see that a `.mod` file will be created along side `linked_list.f08` file
> ![Screenshot_2020-02-29_11-54-02](https://user-images.githubusercontent.com/15893711/75609806-47b34700-5aea-11ea-8a6e-2ba58390d7eb.png)
> This means that the **linter** worked and compiled your file, but having the `.mod`files in `src` folder can become a mess. To solve this, let's use the `-J` flag that redirect the `.mod` to `bin`folder where it belongs. This is done in settings like:
> 
> ```js
> {
>     "fortran.gfortranExecutable": "gfortran",
>     "fortran.linterEnabled": true,
>     "fortran.includePaths": [
>         "/home/pedro/Documents/Codes/LinkedList/bin"
>     ],
>     "fortran.linterExtraArgs": [
>         "-Wall",
>         "-J/home/pedro/Documents/Codes/LinkedList/bin"
>     ]
> }
> ```
> 
> As you can see, other flags like `-Wall` can be passed the same way.
> 
> By excluding that `.mod` created in the `src` folder you can see that by saving/reopening the module file the **linter** will return you errors and warnings but now creating the `.mod` in `bin` dir.

Can this be done in a per project basis? If I do the following setting then all the `mod` files from all my project/folder will be dumped on the same folder. But the temporary mod/.o files should be local to that project.

**Comment by gnikit** [comment]
Not as far as I know, you can use VSCode workspaces and set the -J in the workspace settings. You might also be able to use relative directories although I have not tested that myself.

**Comment by JofreMontferry** [comment]
The following seems to work:
```
"fortran.linter.includePaths": [
        "/mods"
    ],
    "fortran.linter.extraArgs": [
        "-Wall",
        "-J/mods"
    ]
```
Does that mean that relative paths have been added?
