### ISSUE TITLE
Syntax highlighting fails at inline forall statements

### ISSUE THREAD

**Issue by ChrisspyB** [krvajal/vscode-fortran-support#169]
Hi all - nice extension, thanks for your work in maintaining this repo.

The syntax highlighting appears to be incorrect for `forall` statements that consist of only one line. Please see the following example:

![Screenshot 2020-04-08 at 17 26 27](https://user-images.githubusercontent.com/8879093/78808981-259cc680-79be-11ea-9a02-dc89975b24db.png)

In line 4, `arr(i) = i * i` has been highlighted in red, even though this is valid syntax and the file compiles (gfortran). The error propagates to other parts of the program too: notice that the `end` statement is also no longer highlighted here. For comparison, compare with the highlighting when the `forall` removed.

![Screenshot 2020-04-08 at 17 26 37](https://user-images.githubusercontent.com/8879093/78808979-25043000-79be-11ea-962c-c6679b0825cc.png)

In more complex files, this error propagation becomes quite severe, causing a large number of syntax-highlighting issues, rendering some files almost unreadable.

Many thanks.

**Comment by pedro-ricardo** [comment]
Thank you for the report and Fix :+1 
This will be released in #167.
