### ISSUE TITLE
How to set the number of characters indented of tabs？

### ISSUE THREAD

**Issue by yaohong772** [krvajal/vscode-fortran-support#171]
I want to change the number of characters in TAB auto indent to 2, how to set？

**Comment by pedro-ricardo** [comment]
This is not a feature of this extension, is a global parameter.
- Open your `Settings` 
- Search for "tab size"
- Type 2 (default is 4)

As in the picture below:
![Screenshot_2020-04-17_16-11-44](https://user-images.githubusercontent.com/15893711/79605562-8450f700-80c6-11ea-8eaa-0f1b6b6616f6.png)

See ya :+1:

**Comment by pedro-ricardo** [comment]
Please close this if it solved.
