### ISSUE TITLE
Single quotes in README settings

### ISSUE THREAD

**Issue by sujona** [krvajal/vscode-fortran-support#174]
Thanks for this plug-in, this is a trivial issue! I wanted to add linter options and copied the line 
`"fortran.linterExtraArgs": ['-Wall'],` 
from the README into the JSON settings. But you actually need double quotes like 
`"fortran.linterExtraArgs": ["-Wall"]`.
Same for `"fortran.gfortranExecutable": '/usr/local/bin/gfortran-4.7',`.

**Comment by pedro-ricardo** [comment]
Thank you.
