### ISSUE TITLE
Support ${workspaceFolder} in includePaths and linterExtraArgs

### ISSUE THREAD

**Issue by dnwillia-ansys** [krvajal/vscode-fortran-support#176]
This variable is supported by other code parsers (eg: C++ parser from Microsoft).  It would be great if it was working since it allows teams using VS code to keep a single project `settings.json` file in the git repo and have team members clone to wherever they like.  For example:
```
"fortran.includePaths": [
  "${workspaceFolder}/myincludes",
  "${workspaceFolder}/mymodules" ],
"fortran.linterExtraArgs": [
  "-J${workspaceFolder}/mymodules"]
```
then it would just work.

Looks like maybe a straightforward change [here](https://github.com/krvajal/vscode-fortran-support/blob/master/src/features/linter-provider.ts) at the bottom of the file?

**Comment by pedro-ricardo** [comment]
That's a good suggestion :+1: 
I'll need to search for a reference in other extensions to know how to interpret the sting and get that `${workspacePath}` value.
Doesn't sound complicated.

**Comment by dnwillia-ansys** [comment]
Great, thanks.  Seems I made a mistake though, the correct variable is ${workspaceFolder}

**Comment by dnwillia-ansys** [comment]
Looking at [this link](https://code.visualstudio.com/api/references/vscode-api#workspace) seems what you want is `vscode.workspace.workspaceFolder[0]`

**Comment by nyckmaia** [comment]
The variable "${workspaceFolder}" is now working in "fortran.includePaths".

Is the a solution?

**Comment by gnikit** [comment]
As far as I can tell, for this to be functional and general a bit more work will need to be done since the paths in `includePaths` would still need to be resolved for ${workspace} variables, similarly to how it is done in the C++ extension.
Same applies for `linterExtraArgs`.

I see what I can come up with although I will admit that TypeScript is not my strong suit

**Comment by gnikit** [comment]
This is now in `v2.6.1` available in the VS marketplace. Also glob patterns in include paths are now supported but be careful not to give overly general globs because gfortran has a limit to the number of arguments it can have during compilation.
