### ISSUE TITLE
Indentation level after preprocessor directives

### ISSUE THREAD

**Issue by sujona** [krvajal/vscode-fortran-support#177]
It would be nice to give preprocessor directives (starting with `#`) no indentation automatically, while while the next regular code line keeps the indented level preceding the preprocessor directive. Like 
```
        var = var*2     ! (*)
#define TEMP sqrt(var)
        var = TEMP      ! same indentation as (*)
```
Thanks a lot!

**Comment by GNikit** [comment]
I think there is an issue that is already open asking for the same feature see #135

**Comment by sujona** [comment]
What I'm asking about is not code folding though. My point is that it would probably be not too hard to make lines starting with # go to the left margin, without affecting the surrounding indentation level. That would suffice since most most such directives you put inside the code are usually
#define, #ifdef-#else-#endif or similarly and they usually are single-line statements, with regular code (which you want on the original indentation level) around/between them.
________________________________

**Comment by gnikit** [comment]
What you are asking as far as I am aware is not valid Fortran code and hence will not compile.

>All fpp preprocessor directives start with the number sign (#) as the first character on a line. White space (blank or tab characters) can appear after the initial "#" for indentation.

https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/fpp-preprocessing/using-fpp-preprocessor-directives.html

**Comment by sujona** [comment]
@gnikit The statement that you are citing is consistent with my feature request. As you can see in the my example above, the # is the first character on the line.

**Comment by gnikit** [comment]
@sujona I have opened a feature request in VSCode https://github.com/microsoft/vscode/issues/137157 but they require 20 upvotes on the issue. I doubt that we will be able to get that given how small our audience is. Anyway, spread the word.

**Comment by gnikit** [comment]
@sujona vscode rejected the feature request, so I will be closing this for now. Maybe I will advertise it in Fortran discourse to try and reopen it in the future.
