### ISSUE TITLE
inconsistent syntax highlighting for nested case-selects

### ISSUE THREAD

**Issue by gnikit** [krvajal/vscode-fortran-support#181]
The Modern Fortran 2 extension by @pedro-ricardo in the VS code appears to have a bug with syntax highlighting which is not present in the main Modern Fortran extension, see `case(2)` colouring in the figure below. Also, the highlighting with the `fortran-language-server` through the extension FORTRAN IntelliSense appears to be partially broken but I will raise this as a separate issue.
![image](https://user-images.githubusercontent.com/16143716/82372954-c1394200-9a14-11ea-9bad-fe54d46e76b2.png)

**Comment by pedro-ricardo** [comment]
Thanks for the report @GNikit :+1: ,
The `select case` received the update #165 and I don't remember testing two `select case` inside each other.
Will look at it
