### ISSUE TITLE
Modern Fortran 2: erroneous syntax highlighting when used in combination with FORTRAN IntelliSense (fortls) and hovering

### ISSUE THREAD

**Issue by GNikit** [krvajal/vscode-fortran-support#182]
Changes added to Modern Fortran 2 cause the following behaviour when used in combination with the fortran-language-server extension for VS code.

![Screenshot from 2020-05-19 21-16-28](https://user-images.githubusercontent.com/16143716/82374291-c0091480-9a16-11ea-9e56-0d2d00dc3b13.png)

It's worth mentioning that it looks awfully similar to [this](https://github.com/hansec/vscode-fortran-ls/issues/21) bug reported in the fortran-language-server extension for VS code.

**Comment by pedro-ricardo** [comment]
@GNikit Thanks for the report
In this new Release we added some options to prevent weird behaviors with Intellisense extension.
Please check your settings and uncheck hover and the others that conflict with Intellisense.

**Comment by pedro-ricardo** [comment]
Please **uncheck** all of these here:
![Screenshot_2020-05-19_17-38-11](https://user-images.githubusercontent.com/15893711/82375826-88d73b00-99f7-11ea-905a-1946442f6057.png)

The reason why it wasn't happening before is due to the extension features `completion`, `hover` and `symbos` where not working.

**Comment by GNikit** [comment]
As far as I can tell, using the following settings
``` json
    "fortran.provideSymbols": false,
    "fortran.provideCompletion": false,
    "fortran.provideHover": false,
    "fortran.linterEnabled": false, // debatable, had it true in the past
```
the problem still persists.

As a side note, when enabling hover and completion (with fortls disabled) I see no difference.

**Comment by pedro-ricardo** [comment]
hehehee ... it's funny, I think I found,
This is a bug in Language Server, the same that [you linked](https://github.com/hansec/vscode-fortran-ls/issues/21).
The solution for that in their extension was this one:
```
if (extensions.getExtension('krvajalm.linter-gfortran')) {
	haveMFortran = true;
}
```
And now this fortran extension has a different publisher `pedro-ricardo.linter-gfortran`
So the fix wont work.

**Comment by pedro-ricardo** [comment]
I'll contact them and reopen the issue.
:+1: Thanks again for the feedback

**Comment by pedro-ricardo** [comment]
Close this if you agree with it
