### ISSUE TITLE
Disable automatic creation of .mod files

### ISSUE THREAD

**Issue by llamm-de** [krvajal/vscode-fortran-support#187]
It seems like the app provides some functionality, which automatically creates .mod files as soon as one opens a module source file. 
This can get really annoying if you are working on a large project with lots of modules, which are not supposed to live within the same directory as the source files (e.g. by using CMake's Fortran_MODULE_DIRECTORY flag).

Is there a way to turn this automatic creation off? If not, I would like to suggest to implement such a feature.

Thank's for your help.

**Comment by han190** [comment]
Hi, go to `settings.json` and type the following
```
// Fortran
"fortran.gfortranExecutable": "",
```
It should work.

**Comment by llamm-de** [comment]
Hey,

thanks for this small hack. Unfortunately, the solution comes with the drawback of not getting any more compiler errors displayed within vs code. It would therefore be great, if there would be another solution.

**Comment by gnikit** [comment]
@llamm-de did that solve your problem? If so are you happy with closing the issue?

**Comment by gnikit** [comment]
I suspect this issue has been resolved, so I will be closing it. Feel free to reopen if you are still having problems.
