### ISSUE TITLE
Modern Fortran task.json

### ISSUE THREAD

**Issue by jehosafatc** [krvajal/vscode-fortran-support#188]
Hello, 

I was just wondering if you could send me or post an example of a tasks.json that will compile Fortran code with gfortran? I am a Mac user and tried different combinations of the tasks.json but nothing seemed to work. I kept getting different errors. 

Thank You

**Comment by llamm-de** [comment]
Hey,

I got an example online for my colleagues at the institute. You can find it [here](https://github.com/llamm-de/VSCode_Fortran_Tutorial/tree/master/episode_3). Unfortunately, this has only been tested under linux. But maybe you can get something out of it.

Best regards.

**Comment by amfox37** [comment]
{
    "version": "2.0.0",
    "_runner": "terminal",
    "tasks":[
        {
            "label": "build_gfortran",
            "type": "shell",
            "command": "gfortran",      
            "args": [
                "-g",
                "${file}",
                "-o",
                "${workspaceRoot}/${fileBasenameNoExtension}.exe"
            ],
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ],
  }

**Comment by gnikit** [comment]
In general, `task.json` files for Fortran are very similar to the C/C++ VSCode so you can always have a look there (https://github.com/microsoft/vscode-cpptools) for more info
