### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mtesseracted** [krvajal/vscode-fortran-support#189]
- Issue Type: `Bug`
- Extension Name: `linter-gfortran`
- Extension Version: `2.2.1`
- OS Version: `Linux x64 5.4.0-42-generic`
- VSCode version: `1.47.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

This extension is crashing and causing my vscode to be unresponsive.

**Comment by mtesseracted** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 56,
		"activateCallTime": 58,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "krvajalm.linter-gfortran",
				"_lower": "krvajalm.linter-gfortran"
			},
			"activationEvent": "onLanguage:FortranFreeForm"
		}
	},
	"runtimeErrors": []
}
```

**Comment by gnikit** [comment]
I am afraid that more information will be needed for us to be able to help. 
Useful information often include, the error message, what you were doing when the extension crashed and a series of steps for us to be able to reproduce it. The last one being the most important one.

**Comment by gnikit** [comment]
I will be closing this issue. Please reopen if you are still having problems.
