### ISSUE TITLE
Remove old version of the extension form the Marketplace

### ISSUE THREAD

**Issue by phil-blain** [krvajal/vscode-fortran-support#195]
This extension is published on the VSCode marketplace as :

https://marketplace.visualstudio.com/items?itemName=krvajalm.linter-gfortran

but an older version is available with a different itemName:

https://marketplace.visualstudio.com/items?itemName=krvajalm.fortran

The second one is the old one (stuck at version 0.4.5) and should be removed from the marketplace because it's confusing when you search for "Fortran" and find two similarly-named extensions.

---

Thanks a lot for this extension! I use it daily :)

**Comment by gnikit** [comment]
I suspect you mean this one:

----

Name: Modern Fortran
Id: krvajalm.fortran
Description: Modern Fortran language support, including syntax highlighting and error detection.
Version: 0.4.5
Publisher: Miguel Carvajal
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=krvajalm.fortran

@krvajal could you have a look when you get the some time?

**Comment by gnikit** [comment]
This has been resolved. I am closing this issue now.
