### ISSUE TITLE
Fortran Highlight Issue

### ISSUE THREAD

**Issue by han190** [krvajal/vscode-fortran-support#196]
Hi, thank you for this excellent work! This extension has been super helpful writing Fortran code.

Now I have a small issue relating to the highlight of `.f90` file. Wherever the keyword `class` appears, only the left parenthesis is highlighted. The right parenthesis is highlighted with a different color. This issue only occurs when I am using the [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme). A screenshot that demonstrates the issue is attached below.

The OS I am using is the WSL2(Ubuntu 20.04) under Windows 10.

![Capture](https://user-images.githubusercontent.com/13799118/95646224-c6099b80-0a72-11eb-8eea-5017de425e28.PNG)

**Comment by gnikit** [comment]
Hi @han190 I think this should be fixed. For me it looks something like this

![image](https://user-images.githubusercontent.com/16143716/99193178-2b863180-276f-11eb-9c3b-8c461aec5836.png)

Please do let me know if you still are having problems

**Comment by han190** [comment]
Hi, @gnikit I just checked on my laptop and problem is fixed. Thank you!
