### ISSUE TITLE
Allow custom regex for line comments

### ISSUE THREAD

**Issue by Aralox** [krvajal/vscode-fortran-support#197]
Hi there, we have a large Fortran codebase at my company, mostly fixed-form, written in the 80s and 90s. We have some fancy extra syntax and 'transpile' all of our files to ".f.f" before compiling it. In the untranspiled form, we use a different specifier for line comments: ";*". E.g. `if (SOMETHING) go to 110		;* this is a comment`. Ordinarily I'd just ignore the lack of highlighting for the comment, but the problem is when there is a single quote in the comment, the highlighter thinks it is the start of a string, and will subsequently highlight all following code as a string until it sees another single quote.

![image](https://user-images.githubusercontent.com/8370997/95945628-9c67c000-0e36-11eb-9366-8fb4da8d9a3c.png)

For large blocks of code, this is very frustrating. I have tried many different vscode Fortran syntax highlight extensions, but none of them avoid this problem. There are always large swathes of incorrectly highlighted code.

I've found that I can edit %userprofile%\.vscode\extensions\krvajalm.linter-gfortran-2.2.1\syntaxes\fortran_free-form.tmLanguage.json
And change line 865 from
`begin": "!",`
to
`"begin": "!|;\\*",`

Which solves my problem. This is what it looks like after my change:
![image](https://user-images.githubusercontent.com/8370997/95945901-329be600-0e37-11eb-804c-a521bae7dde3.png)

I would like to contribute this back to the repo.
What is the best way to do this? Should I make this an extension setting and expose the whole free-form comment.line regex to the user?

I am keen to open a PR for this as part of Hacktober. :)

Thanks!

**Comment by gnikit** [comment]
Hi @Aralox you might want to have a look at the [better-comments](https://github.com/aaron-bond/better-comments) VS Code extension and possibly raise the issue with them about using custom comment characters. If I remember this PR in better-comments aims to do something similar https://github.com/aaron-bond/better-comments/pull/127

Also, I think the author of better-comments has yet to merge a fix for the extension to do what is supposed to (fancy highlighting) in modern fortran see https://github.com/aaron-bond/better-comments/pull/186, but that shouldn't really matter in your case.

**Comment by Aralox** [comment]
Thanks for the suggestion @gnikit. I gave it a go but it seems to clash with Modern Fortran's highlighting. In any case, I think even if it could be modified to support custom comment characters, I don't think it'd help with my problem. The rest of the code's highlighting (excluding comments) is still handled by Modern Fortran, and if there's a single-quote in the comment (regardless of whether it is highlighted by another extension), it will think that's the beginning of a string block, and wrongly color all following code.

**Comment by gnikit** [comment]
The problem with this one is that the `;` character is a non-standard comment character and in actuality it is used as a statement separator so it would be incorrect (generally speaking) to use it as a comment indicator [see](https://gcc.gnu.org/onlinedocs/gcc-3.2.3/g77/Statements-Comments-Lines.html)
