### ISSUE TITLE
Working on big projects and using makefiles

### ISSUE THREAD

**Issue by stefabat** [krvajal/vscode-fortran-support#209]
Hi

I am working on a quite large project and I am not sure how to take full advantage of the extension. For instance, right now I only get the syntax highlight to work, but no code completion or linting.
Some context:
I open vscode in the root folder of the project. Source code is in `root/src`, while I build the project in a separate terminal (or with a vscode task that I setup) in `root/build` using `cmake` to generate a bunch of makefiles, and then `make`.

I am not sure which of the extensions settings I am supposed to modify to make code completion and linting work.
I could not find it explained in the README either, if this will work in the end, I am happy to contribute and document the steps necessary to cases similar to mine.

**Comment by stefabat** [comment]
Never mind, I think what is the issue. With fixed-format it does not work, only with free-format.
On the other hand, in combination with the language server it works fine and out of the box, hence I close this issue.

**Comment by pedro-ricardo** [comment]
Hello there, 
As you said the language server will get the auto complete to work properly, but if you want the linter to give you warnings/errors in big projects, I suggest that you follow this tutorial [here](https://github.com/krvajal/vscode-fortran-support/issues/159#issuecomment-592954220) it is simple and will get the linter to work.
