### ISSUE TITLE
Symbol List uses 100% CPU

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#21]
In large files the **Symbol List** (Ctrl-Shift-O) fails too, CPU goes to 100%, and VS-conde needs to be killed manually.
In this case i think it is because the extension mark as a symbol all declared variables and functions on the file, instead of only the keywords _function_, _subroutine_, _program_ and _module_.
In my opinion, to take all variables as symbols isn't correct, but let's discuss this ...

**Comment by krvajal** [comment]
I personally like to have the variables available as in the symbol list,  but what about making it optional and disabled by default?

**Comment by krvajal** [comment]
Regarding the perf issue, I have changed the implementation to be async so your editor should not hang anymore. After getting your feedback regarding the variables in the symbol list I will push an update so we can check if the perf issue is fixed. 😃

**Comment by pedro-ricardo** [comment]
I agree with you that it shoud be optional, but i'm not shure it shoud be disabled by default @krvajal. Maybe it's just my files that are too large and the way it is looks good for everyone else. I suggest that this new flag turn's off just the variables as symbols not the other keywords like. _function,_ _subroutine,_ _program_ and _module_.

**Comment by krvajal** [comment]
Please @pedro-ricardo,  if you have some time check version `v0.6.3` and let me know if the performance problem is solved.

**Comment by pedro-ricardo** [comment]
I checked and still have problems with large files ...
If I disable all flags the (Ctrl+Shift+O) works fine and writes "No symbols found",
but when enable "functions" or "subroutine" it stops again. I will mail you the file so you can test on it.

**Comment by krvajal** [comment]
I have checked and indeed when the file is very large (very common in the Fortran programming world) it takes a lot of time to process it. My current implementation is not very optimized and I have two options to move forward:
1) Improve my current implementation until getting a reasonable speed
2) Use `ctags` that is very solid, fast and well-maintained program, but it will add another binary dependence on the extension and user will have to install it themselves.

The second option will allow me to have a working implementation for #4 as well.
Maybe I could include both and add a config option to allow the use of `ctags`.

**Comment by krvajal** [comment]
The issue has been fixed and it turns out to be a 🐛  in the regex used to determine the `subroutine`.  I tested it with the problematic file and it seems to work as expected.

**Comment by krvajal** [comment]
@pedro-ricardo  please let me know if the problem is solved on your side so I can close this.

**Comment by pedro-ricardo** [comment]
Everything working like a charm!! And it is much faster now. Thank you very much....
