### ISSUE TITLE
Windows: Cannot open module file "/tmp/myfile.mod0" When -J option is used.

### ISSUE THREAD

**Issue by lurobi** [krvajal/vscode-fortran-support#210]
This was raised previously: https://github.com/krvajal/vscode-fortran-support/issues/187

I'm re-raising it for two reasons:
1) I find the sudden creation of a .mod file after editing something to be surprising.  This doesn't happen for instance with .o files.  There isn't any documentation suggesting this might happen.
2) Extraneous .mod files can cause build failures.  Build systems will see that the .mod file is up to date when doing dependency checking, despite the fact that the linting-compile may have very different flags from the intended build.  This issue in particular is what caused problems for me.

As far as a solution I couldn't think of a good one.  It would probably be ideal if gfortran offered a "don't create modules" flag.  I tried the `-fsyntax-only` option but it still creates modules.

The work-around mentioned in the previous issue was to use something like -J/tmp to write module files to a throw-away path, but attempting this solution provides an error `Cannot open module file "/tmp/myfile.mod0" for writing`.  Notice the extra 0 on the end, I'm not sure why it is there.

**Comment by pedro-ricardo** [comment]
Have you tried `/dev/null` instead of `/tmp` ?
**gfortran** can not compile and don't create the `.mod` file unfortunatly. I've looked for it once.
The `/dev/null` was the solution found at their forums. And it worked on VSCode.

**Comment by pedro-ricardo** [comment]
Ok ... let me correct the previous comment. `/dev/null` won't help you as well, it just causes an error and the compiler returns nothing, seems to work but it doesn't.

Think of the `.mod` like an automatic `.h` header file. They simply exist as part of a Fortran compilation.
I undestand that mixing the linter compilation with your makefile one can cause issues.

The attempt on `/tmp` was becouse it usually holds data that is not needed, but maybe in your system this is not the way. Do you even have a `/tmp` folder?

The solution is to point this `-J` option to a folder that exists but it's temporary .. either you can create your own to hold this kind of stuff, or find were your operating system dispose temporary files and send it there.
The `/tmp` folder is a solution for Linux systems.

**Comment by lurobi** [comment]
Yes, thank you. I concluded the same thing, that -J should be the solution, although perhaps it's something with my windows set up, but I can't get any -J directory to work, they all error with a similar complaint.  I've tried both C:\ and /c and /tmp, all of which could be paths recognized by gfortran running within MSYS.

**Comment by pedro-ricardo** [comment]
Ok so it's windows. Can you change the title and insert like "for windows" in it ?
I'll find a Windows setup with Msys to try helping ya.
Cat you send me a few settings? Like how are you calling gfortran? Are you using any flags that require a directory, like `-I` or `-L` .. how do you set the folders.
Is vsxode in

**Comment by pedro-ricardo** [comment]
Sry .. the closing was a missclick 😁

**Comment by lurobi** [comment]
Looks like I was to blame, not sure why I couldn't get this to work previously.  The following linter extra arg works fine for me now.  It does want a valid Windows path with paths escaped properly.

Does this variable accept things like `${workspaceFolder}` ?

```json
    "fortran.linterExtraArgs": ["-JC:\\my\\own\\tmp"],
    },
```

OK to close.
