### ISSUE TITLE
Active text editor doesn't provide symbol information

### ISSUE THREAD

**Issue by popovas** [krvajal/vscode-fortran-support#214]
issue occurs whenever i try to go to symbols (functions/subroutines), e.g. using ctrl+;

code is fortran 2008/2018 standard

**Comment by gnikit** [comment]
Can you confirm that you have `"fortran.provideSymbols": true` in your settings. If so, could you attach your settings relevant to the Modern Fortran extension from your `settings.json` and also provide a sample test code to reproduce the error

**Comment by gnikit** [comment]
I will be closing this issue now. Please reopen if you are still having problems.
