### ISSUE TITLE
Debugger does not stop at breakpoint

### ISSUE THREAD

**Issue by baojd42** [krvajal/vscode-fortran-support#221]
I have a piece of  Fortran code and try to learn how to debug, however the debugger does not stop at the breakpoint but launches the program and runs to the end. Could any body please help me to figure out what's going wrong?

1. The code and breakpoint:
![image](https://user-images.githubusercontent.com/33564834/110906355-cc17e700-8346-11eb-8cad-a91c6cf61f45.png)
2. Debugger configuration:
![image](https://user-images.githubusercontent.com/33564834/110906885-93c4d880-8347-11eb-9437-4021a6df322f.png)
3. Output in debug console:
![image](https://user-images.githubusercontent.com/33564834/110908780-426a1880-834a-11eb-9f29-824c8f582d1d.png)
4. Output in terminal:
![image](https://user-images.githubusercontent.com/33564834/110908942-79d8c500-834a-11eb-96f8-9862a6997ab4.png)
5. Tools and extensions I am using:
gfortran -- (Debian 8.3.0-6) 8.3.0
vscode -- 1.54.2
Modern Fortran extension -- 2.2.2
C/C++ extension -- 1.2.2

Thanks!

**Comment by gnikit** [comment]
You need to compile with debug symbols enabled, i.e. use the flag `-g`. That is a common reason why the debugger won't work.

**Comment by baojd42** [comment]
@gnikit Many thanks! This little flag also solved another problem of mine. Thank you again and wish you good weekends!
