### ISSUE TITLE
Can't force the extension to treat .f files as free form fortran

### ISSUE THREAD

**Issue by sbrisson-sudo** [krvajal/vscode-fortran-support#222]
When making VS code  to associate .f files with the FreeFormFortran language Id, the extension use the free form syntax highlighting but the fixed form error detector.

User settings.json modification:

```json
 "files.associations": {
        "*.f": "FortranFreeForm"
    },
```
Without modification:
![Without modification](https://user-images.githubusercontent.com/80926815/114267000-b9eaa080-99f9-11eb-9e27-252904b9cf86.png)
With modification:
![With modification](https://user-images.githubusercontent.com/80926815/114267001-ba833700-99f9-11eb-98b1-092d0f6d9cea.png)

**Comment by gnikit** [comment]
I see. This is actually `gfortran` assuming it's default options. I will add it on the todo list of things to look at, but an easy way to fix this would be to pass `-free-form` as an argument to `"fortran.linterExtraArgs: [ "-free-form"]`"

See [here](https://gcc.gnu.org/wiki/GFortranGettingStarted) for `gfortran` default options for file extensions.

**Comment by sbrisson-sudo** [comment]
Oh right, that work perfectly thank you for your time!

**Comment by gcamporredondo** [comment]
I am dealing with the same issue. Extension changed, highlighted ok, and Makefile adapted but gfortran will not go compile .f extension files, only .f90. Any idea?
