### ISSUE TITLE
New feature: Code folding based on keywords not tabs

### ISSUE THREAD

**Issue by dfousek** [krvajal/vscode-fortran-support#223]
Hi ! 
I am using already this plugin and thanks for that.
How difficult would it be, to add code folding based on fortran statements (ie: subroutine....end subroutine, program....end program, do i-1,10....enddo, if....endif) ?
An added degree of difficulty is the exclusion of preprocessor commands ($if, $declare, etc) which must be in the 1st column, from the code folding.
Kind regards,
Dimitri

**Comment by gnikit** [comment]
I think there is an existing feature request for this here https://github.com/krvajal/vscode-fortran-support/issues/135 .
If that is what you are asking I would suggest +1 the issue and closing this one.

Having said that, VS Code supports what you are asking so it is a matter of implementing it in the extension, which might take some time for us to get around. If you want you can have a crack at it yourself in a PR.

**Comment by dfousek** [comment]
Yes, indeed, it is the same request as #135
