### ISSUE TITLE
OpenMP continuation not triggering correctly

### ISSUE THREAD

**Issue by jefflarkin** [krvajal/vscode-fortran-support#225]
While I was testing the OpenACC directive support I discovered that the OpenMP continuation (and thus the OpenACC continuation) does not highlight properly if the optional `&` appears on the continued line's sentinel. I tried to debug this myself as a part of the PR, but even with a few sets of eyes on it I wasn't able to get it working.

```
!$omp parallel &
!$&omp do 
```

For the above code, if either `&` is left off the `do` will appropriately highlight, but if both are in place it does not. The specification allows for the ampersand on the sentinel and this is how I've seen it used in every code I've encountered.

**Comment by gnikit** [comment]
I think the solution to that might be similar (or hopefully identical to https://github.com/krvajal/vscode-fortran-support/pull/203).
If that is the case and you decide to fix it yourself would you mind to mention https://github.com/krvajal/vscode-fortran-support/pull/203 in the commit message so this code duplication is somewhat traceable in the git logs?

We really ought to find a better way to implement the syntax highlighting

**Comment by jefflarkin** [comment]
It looks like re-using that fix did do the trick. I had intended to submit a separate PR, but accidentally included the fix in #224 .

**Comment by gnikit** [comment]
Glad to hear that. I will have a look at the PR
