### ISSUE TITLE
gdb debugger allocatable arrays not shown

### ISSUE THREAD

**Issue by f-L0x** [krvajal/vscode-fortran-support#226]
Hi,

I'm using the gdb debugger with gfortran with vscode on windows.
As compiler args I only used `-ggdb -Wall`

Here allocatable arrays are not shown correctly in the debugger.
To be more exact: There is always just a `[0]`

The program itself works fine.
I can print the allocated array.

I'm not sure were this problem is located: gdb, gfortran or vs code extension
But I can't find a workaround.

![image](https://user-images.githubusercontent.com/56804629/115994500-83a34880-a5d7-11eb-8331-46f85d7e41cd.png)

In `launch.json` I use the default setting.

Here little test program:
```
program horst

    implicit none

    integer :: n, n_max
    integer, dimension(4)              :: n_sqrt
    integer, dimension(:), allocatable :: n_sqrt_alloc

    n = 1
    n_max = 4
    allocate(n_sqrt_alloc(n_max))

    do n=1, n_max
        n_sqrt(n) = n**2
        n_sqrt_alloc(n) = n**2
    end do

    write(*,'(A,4(I3))') 'not allocatable:',n_sqrt
    write(*,'(A,4(I3))') 'allocatable:',n_sqrt_alloc

    write(*,*) 'works fine, but not in the debugger'

end program horst
```

**Comment by gnikit** [comment]
My guess would be that your binary might be out of date and GDB is struggling to associate it with your later modified source file.
Make sure that the binary you are debugging reflects your latest source file, i.e. you haven't modified your .f90 after compilation. 

To automate that you can create a build task `tasks.json` that will be calling your build system whatever that is.
Here is an example that calls `make -j`, you can substitute that with a `sh ./build.sh` or `gfortran -g -Wall horst.f90`.
The you can call the build task through VS Code.

```cjson
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "compile",
      "type": "shell",
      "command": "make",
      "args": [
        "-j"
      ],
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": [
        "$gcc"
      ],
    },
  ]
}
```

Could you give that a try and let me know how it goes?

FYI

I tried the example that you posted and it seems to work okay
![image](https://user-images.githubusercontent.com/16143716/115996372-da5c5280-a5d6-11eb-82bf-663bac9d3e72.png)

**Comment by f-L0x** [comment]
Thanks for the fast response.

But unfortunately this doesn't solve it.
This was exactly what I tried my times. 
Used a `build.sh` or direct in terminal `gfortran -g -Wall`. Deleted all files. All results in the same probelm.
I also tried it on another windows machine with the same `MinGW` installed on it.... Same Problem

**Comment by f-L0x** [comment]
I installed another MinGW Version. 
Now it works. 
Sorry for the confusion.
