### ISSUE TITLE
Use out-of-source directory for .mod files by default

### ISSUE THREAD

**Issue by apthorpe** [krvajal/vscode-fortran-support#231]
This is an enhancement request related to both #176 and #187 

By default the linter runs gfortran against source code in the directory where it is found, generating `.mod` files in those directories. This works fine until you use an out-of-source build system like CMake. The `.mod` files written by the linter into the source tree interfere with compilation and linking under CMake and complicate version control.

The workaround is to manually tell the linter to write `.mod` files to a separate out-of-source directory and to include that directory for the linter's use.

An example: For a project with the base directory `C:/Users/me/Documents/git_projects/my_project`, I will create the directory `.fmod` under the project root (`C:/Users/me/Documents/git_projects/my_project/.fmod`). I then modify the workspace's `settings.json` to add:

```json
    "fortran.linterExtraArgs": [
        "-JC:/Users/me/Documents/git_projects/my_project/.fmod"
    ],
    "fortran.includePaths": [
        "C:/Users/me/Documents/git_projects/my_project/.fmod"
    ],
```

This gives me the benefit of linting and syntax checking while keeping temporary files out of my source directory.

The big problem is that I have to manually configure every project like this if I want to use both CMake and Fortran linting.

It seems like this could be easily solved by setting the default configuration to something like:

```json
    "fortran.linterExtraArgs": [
        "-J${workspaceFolder}/.fmod"
    ],
    "fortran.includePaths": [
        "${workspaceFolder}/.fmod"
    ],
```

The directory `.fmod` needs to be created. There may be issues using a single directory to store files generated from a source tree if the source tree contains multiple files with the same name. In that case, replicate the source directory structure under `.fmod`. That is, for the source directory `${workspaceFolder}/.fmod/src/tree`, set the include path and `-J` path to `${workspaceFolder}/.fmod/src/tree`. This is slightly more complex but would solve the problem for projects with multilevel source directories, the sort of complex projects CMake was designed to manage.

If #176 adds `${workspaceFolder}` support, this change would be an invisible resolution of #187.

**Comment by bertrandcz** [comment]
+1, this workaround works perfectly, thanks.

**Comment by gnikit** [comment]
The out-of-source directory option has been added to `v2.6.1` available in the VS Marketplace. It is not the default behaviour for the reasons stated above but you can define a custom directory for the mod output by setting the variable `fortran.linterModOutput` in the settings. You will still have to include the `fortran.linterModOutput` directory into your `fortran.includePaths`. Luckily path interpolation and glob support are also available now so setting up projects should be noticeably easier.
