### ISSUE TITLE
Exclude certain module from linter

### ISSUE THREAD

**Issue by ollehellman** [krvajal/vscode-fortran-support#233]
Hi,

I wonder if it would be possible to exclude certain module names from the linter? For example, when writing parallel code I tend to have
```
use mpi
```
in many files, and consequently get the error that the file `mpi.mod` can not be found. Since it's an external library that I assume is fine, it would be nice to have a feature that does something like "ignore module XXX".

**Comment by gnikit** [comment]
I simply tend to ignore these problems, but I will see what can be done either by suppressing the error and/or resolving it when the external module is included

**Comment by gnikit** [comment]
Getting back to this.
The errors for the missing `mpi.mod` are valid and should not be ignored. As in, gfortran does not automatically include the path where `mpi.mod` is located and that's what the linter is saying. You need to configure your linter through `fortran.includePaths` and `fortran.linterExtraArgs` with the same parameters that you would use to compile your code.

There is a PR in the works were it makes the inclusion of arguments way less painful than it currently is, but until that is complete you will have to will have to specify each include directory (same way that you would do with a Makefile).
