### ISSUE TITLE
Support for Title Case

### ISSUE THREAD

**Issue by thomas-mac** [krvajal/vscode-fortran-support#234]
As an alternative to lowercase and UPPERCASE Fortran keywords, some codes use Title Case keywords. It would be great if this was added as a third option.

**Comment by gnikit** [comment]
Important to note here is that this would only affect the autocompletion of keywords and nothing else since the hover symbols are provided by the fortran-language-server which only supports upper and lower case.

We can still add it as a feature though

**Comment by gnikit** [comment]
There are currently no plans to implement title case keywords, so I will be closing this issue.
