### ISSUE TITLE
Setting up VSCE releases from GitHub releases

### ISSUE THREAD

**Issue by gnikit** [krvajal/vscode-fortran-support#237]
I think it would make things a bit easier if we managed to set up a way to issue VS Code Marketplace releases through the GitHub.
https://code.visualstudio.com/api/working-with-extensions/continuous-integration#automated-publishing

I think currently the versioning is a bit out of sync between the 2.

@krvajal Any thoughts on how to do this?

**Comment by krvajal** [comment]
Fill free to open a PR, you will need to pass the marketplace token somehow. I can provide it using github secrets.

**Comment by gnikit** [comment]
I had a quick read on how VS Code extensions are published and how could one automate them, and I will admit that I was a bit lost. I will have a more careful read over the weekend to try and figure this out.

**Comment by gnikit** [comment]
An Actions alternative: https://github.com/HaaLeo/publish-vscode-extension
