### ISSUE TITLE
Extension not available for VS Codium

### ISSUE THREAD

**Issue by maxnoe** [krvajal/vscode-fortran-support#240]
I am on arch, so code from the official package repository is actually vs codium.

I cannot find this extension in the package store and running the `ext install` line fails as well.

Would be great if you would also support installing the extension in VS Codium

**Comment by gnikit** [comment]
I am not sure if publishing on open-vsx.org is on the books for the time being. Until then you can use this solution
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace

**Comment by gnikit** [comment]
Duplicate of #190
