### ISSUE TITLE
Fortran Symbols

### ISSUE THREAD

**Issue by kookma** [krvajal/vscode-fortran-support#27]
Please complete the Fortran Symbols outlining!
There are open code in the net can be useful for this regards like Code::Blocks.

**Comment by krvajal** [comment]
What do you mean by Fortran Symbols outline, something like this?

![tree](https://code.visualstudio.com/assets/docs/extensionAPI/extension-points/views.png)

**Comment by kookma** [comment]
That's a tree of Fortran symbols e.g variable, user defined type, class, subroutines, functions, ...
Something similar to the pic you showed!

**Comment by krvajal** [comment]
@pedro-ricardo does this feature sound attractive to you?

**Comment by pedro-ricardo** [comment]
But doing that in the way VSCode let extensions do it, would sacrifice the explorer tab ... and i'm not sure if that is a good idea. Maybe we should wait for Microsoft to let us create a whole new tab before adding this.

**Comment by pedro-ricardo** [comment]
@krvajal  Just found out that this is not our problem ...  This is a very popular feature request in VSCode repo [#5605](https://github.com/Microsoft/vscode/issues/5605). When they implement this, the symbol-list will be on a separate tab already.

**Comment by pedro-ricardo** [comment]
Pretty sure we can close this now... It is a new feature of VSCode, on preview but already working with our symbols. It is called outline.
![outline](https://user-images.githubusercontent.com/15893711/42120217-2f227da0-7bee-11e8-927e-5823c87d269c.png)

**Comment by pedro-ricardo** [comment]
@kookma It is that what you were looking for? If yes, could you close this issue?

**Comment by kookma** [comment]
Sure!
