### ISSUE TITLE
Extra linter args not having any effect

### ISSUE THREAD

**Issue by mdinescu** [krvajal/vscode-fortran-support#294]
I have a project that I've setup with Modern Fortran + Intellisense + Fortran Language Server but I am getting a bunch of warnings everywhere, mostly regarding nonconforming tab characters.

    Nonconforming tab character at (1) [-Wtabs]

I've tried setting up the linter extra args, like so:

```
{
    "fortran.linterExtraArgs": ["-Wtabs"]  // also tried -Wall
}
```

But despite setting these options, the linter is still reporting the errors everywhere. It is super frustrating and it makes code browsing difficult and slow(er)

**Comment by gnikit** [comment]
hi, so from what I understand is you want to disable these warnings. You can do that by `"fortran.linterExtraArgs"" []`.
You can also turn on/off specific types of warnings in gfortran by using the `-Wno-` prefix, e.g. `-Wno-tabs` will ignore tab warnings so setting up your linter  `"fortran.linterExtraArgs"" ["-Wall", "-Wno-tabs"]` will show all warnings except the tab related ones.

I hope this helps

**Comment by mdinescu** [comment]
That's exactly what I was looking for. Thank you!
