### ISSUE TITLE
PGI Fortran

### ISSUE THREAD

**Issue by walkerjian** [krvajal/vscode-fortran-support#30]
Hi, thanks for your modern fortran extension. Do you have any advice on how to get PGI fortran working with your addin and vscode? Also, have you experienced any diffulculties with linking programs in the light of rowhammer, and what companies such as apple are doing to aslr and kaslr? Cheers!

**Comment by krvajal** [comment]
Can you clarify what you mean by working?

**Comment by walkerjian** [comment]
As in compiling… I have moved on from this and have started using VS with the pgi addin. I also have various docker containers that I am slowly adapting to use with a gui. It would be great to be able to use vscode with pgi community in a container, or gfortran for that matter. There just seems to be a great deal of difficulty getting a fortran compiler to stick for any length of time in OS X. For me at least…

**Comment by krvajal** [comment]
I am closing this as it is no longer relevant.
