### ISSUE TITLE
Please develop one for Visual Studio 2022

### ISSUE THREAD

**Issue by Ben136KBC** [krvajal/vscode-fortran-support#305]
Your extension is great and works well in Windows with Visual Studio Code, using Intel Fortran Compiled code.

Visual Studio 2022 (not code) has been released and is 64 bit only. There is no Intel Fortran support for it yet, and the support when it does come tends to be glitchy.

It would be utterly marvelous if you can write a Visual Studio extension based on this!

Pretty please?!?!?

**Comment by gnikit** [comment]
I am afraid that VS is a completely separate beast to tackle. I suspect that we would have to write a completely new extension from the ground up and unfortunately, we do not have the manpower, or the free time to develop something like that. All the work that we do here is on our spare time to make our lives easier in our work/research.

You could probably send a feature request to Microsoft and/or Intel, but I wouldn't be too optimistic about them adding support in the near future.
In the meantime maybe this VS2017 extension might be of use to you
https://github.com/michaelkonecny/vs-fortran-ls-client

The only other thing I can add is that we have added native support for Intel compilers when it comes to linting, see https://github.com/krvajal/vscode-fortran-support/pull/293 . These changes are pending review and will be published soon.

**Comment by gnikit** [comment]
For the aforementioned reasons I will be closing this issue now.
