### ISSUE TITLE
Watch variables do not work

### ISSUE THREAD

**Issue by Ben136KBC** [krvajal/vscode-fortran-support#307]
I love this extension. I have Intel Fortran compiled code, and in Visual Studio Code I can put Fortran break points and I can see local variables. THANK YOU!! However, Fortran variables in the watch window do not work. Also, if you hover over a Fortran variable in the editor window, it does not show any value. Even if I right click on a variable shown in the VARIABLES window and choose Add to Watch, the watch window reports that the identifier is undefined.

![image](https://user-images.githubusercontent.com/12629164/143655882-afe1ef48-8d21-4a30-b8f0-9efbee9ac063.png)

**Comment by gnikit** [comment]
I cannot replicate what you are describing. Please fill in the bug report template and also provide a copy of your Modern Fortran and Fortran Intellisense settings.
FYI hover (for now) is provided by FORTRAN Intellisense so you need to have that enabled.

**Comment by gnikit** [comment]
Just to be safe a compiled my example code with both `gfortran` and `ifort` and used the debugger on the binary and it worked for both.

**Comment by Ben136KBC** [comment]
I am getting this in the log, so maybe I need to log this with the C++ extension?

-> (C) {"command":"evaluate","arguments":{"expression":"PROPNO","frameId":1000,"context":"watch"},"type":"request","seq":54}
<- (E) {"seq":2584,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Evaluate","data":{"VS.Diagnostics.Debugger.vsdbg.Evaluation.IsError":true,"VS.Diagnostics.Debugger.vsdbg.Evaluation.Duration":0,"VS.Diagnostics.Debugger.vsdbg.OSFamily":"Windows","VS.Diagnostics.Debugger.vsdbg.Version":"17.0.10813.1 commit:cc7cde042e46d3d2385dda472927d1d9a0837638","VS.Diagnostics.Debugger.vsdbg.WindowsVersion":"10.0.19043","VS.Diagnostics.Debugger.vsdbg.AdapterId":"cppvsdbg"}}}
<- (R) {"seq":2586,"type":"response","request_seq":54,"success":true,"command":"evaluate","body":{"result":"identifier \"PROPNO\" is undefined","presentationHint":{"attributes":["readOnly","failedEvaluation"]},"variablesReference":0}}

**Comment by gnikit** [comment]
I would first try updating/uninstalling/reinstalling the C++ and Modern fortran extensions. Where does this log message show up?

**Comment by gnikit** [comment]
for the following versions your debugger should work:
C/C++: v1.7.1
Modern Fortran: v2.6.2
VSCode: 1.62.3

**Comment by gnikit** [comment]
has this been resolved?

**Comment by Ben136KBC** [comment]
Sadly, no. I am working on creating a small sample to demonstrate but no luck so far. Would it help if I tried to debug your extension? Would you be interested in setting up a meeting so I can show you and maybe you will go "oh i know....you just..."?

**Comment by Ben136KBC** [comment]
Hi, we are compiling under Windows, using ifort and visual C++. Intel Fortran products PDB files and OBJ files. I tried using cppdebug with GDB, but it does not work because GDB does not support PDB files.

**Comment by Ben136KBC** [comment]
I have a small test sample you can reproduce and debug.
![image](https://user-images.githubusercontent.com/12629164/144151284-382b721e-c20d-41af-bceb-cf1e4fe2b1cc.png)

**Comment by Ben136KBC** [comment]
Here is a small test projects. I have it under f:\ConsoleApplication1. Just unzip it, start Visual Studio Code, and open the folde
[ConsoleApplication1.zip](https://github.com/krvajal/vscode-fortran-support/files/7629817/ConsoleApplication1.zip)
r.

**Comment by Ben136KBC** [comment]
Ah I see, it looks like the watch variables are case sensitive, even though Fortran is case insensitive. Is that something you can fix maybe? And also if you look at the original screen shot, there the case was the same.

**Comment by Ben136KBC** [comment]
In order to avoid confusion, let me close this item and submit a new one which demonstrates the issue.
