### ISSUE TITLE
Fortran variables are sometimes not accessible

### ISSUE THREAD

**Issue by Ben136KBC** [krvajal/vscode-fortran-support#310]
Attached a solution which can be unzipped. It contains one C++ file compiled via Visual Studio 2019, and one Fortran file compiled via Intel Fortran, all native Windows code using OBJ / PDB file format. The C++ code calls into the Fortran code.

The Visual Studio Code version and installed extensions is shown in ConsoleApplicaiton4.png

Open the top folder in Visual Studio Code. If you put a breakpoint in the Fortran file in test, it hits it and you can local variables and NOPROP. See ConsoleApplication1.png.

However, now put a breakpoint in the larger method, see ConsoleApplicaiton3.png. Now you cant see any variables.

If you debug this using Visual Studio 2019 with Intel Fortran, you can see all the variables.

Can you please investigate? I can log this with the C++ extension if that is where the problem lies?
![ConsoleApplication1](https://user-images.githubusercontent.com/12629164/144279168-8f431dd5-0e35-499b-a0ca-16b1fbd5583c.png)
![ConsoleApplication2](https://user-images.githubusercontent.com/12629164/144279180-a88fbce9-c150-40c0-8da3-6d74cf568723.png)
![ConsoleApplication3](https://user-images.githubusercontent.com/12629164/144279196-fe4a308a-0fed-4749-8ac2-4e0738c8655c.png)
![image](https://user-images.githubusercontent.com/12629164/144298047-8088ee9f-bab7-4b92-a21c-a7656ce401dc.png)
[ConsoleApplication1.zip](https://github.com/krvajal/vscode-fortran-support/files/7635793/ConsoleApplication1.zip)

**Comment by Ben136KBC** [comment]
You can see the Fortran compiler flags under consoleapplication1\x64\debug\kbclib.fcf. Note that it works fine for "simpler" Fortran methods, but it does not seem to like the bigger beasties.

**Comment by gnikit** [comment]
I will have a look but FYI I am on Linux, so I might have to spin up a VM if I can't replicate the problem on my machine. Also, I feel that I need to mention that VSCode and VS in terms of project setups are vastly different so a 1:1 comparison might not be particularly helpful.

**Comment by gnikit** [comment]
I am not able to replicate the bug on Linux, the debugger (gdb-oneapi) works fine for both cases, I will spin up a VM and see what happens then. 
I also had a look at your ifort compiler flags, there are a lot of options there to unpack, not sure what all of them do but I would start by compiling the program through a terminal with only the most minimal setup. In Linux/Mac that looks something like:

```bash
ifort -c -g -o Fortran1.o Fortran1.f90
icpx -g -o test ConsoleApplication1.cpp Fortran1.o
```

Then use the newly created `test` binary into your VSCode debugger.
For Linux/MacOs this can be done with the following `launch.json` for Windows I think it simpler

```jsonc
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/test",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            // This is only available for Linux and Mac
            "miDebuggerPath": "/home/gn/intel/oneapi/debugger/10.1.1/gdb/intel64/bin/gdb-oneapi",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Comment by Ben136KBC** [comment]
I am sorry for all the effort, where in your extensions is the code the evaluates the watch window? Maybe the issue is really in the C++ debug API to which it must call up, it does it do a lot more?

**Comment by gnikit** [comment]
No need to apologise. Modern Fortran does not have a debug adapter of its own, we plug in to Microsoft's [C/C++ extension](https://github.com/Microsoft/vscode-cpptools) Debug component. We rely on the fact that C++ debuggers understand Fortran, however when it comes to Windows and Intel compilers I am not sure if that is the case and/or you have to use a specific version of the MSVC debugger.

**Comment by Ben136KBC** [comment]
Thank you, yes, we have tons of old Fortran code. I have also logged this issue here:  https://github.com/microsoft/vscode-cpptools/issues/8479

**Comment by gnikit** [comment]
I had a look at the C++ issue you linked, it would appear that there is not much we could do from our end either. 
The only 2 solutions I can think of are 
1. Using gfortran for development and ifort for production
2. Switching your development environment to Linux/WSL and then using ifort with intel-gdb.

Both of them are extremely inconvenient IMO but I don't see another solution.

I will be closing this issue now. Feel free to reopen if you think there is something else that can be done through Modern Fortran.
