### ISSUE TITLE
"class" keyword not highlighted in dummy arguments

### ISSUE THREAD

**Issue by kgerheiser** [krvajal/vscode-fortran-support#32]
The "class" keyword when specifying dummy arguments is not properly highlighted like "type" is
<img width="425" alt="screen shot 2018-03-08 at 23 55 16" src="https://user-images.githubusercontent.com/3209794/37191198-2dc621f2-232c-11e8-8e87-3d5870a63ecb.png">

**Comment by krvajal** [comment]
Fixed in #42
