### ISSUE TITLE
Support for Fortran 2008 block construct

### ISSUE THREAD

**Issue by kgerheiser** [krvajal/vscode-fortran-support#36]
Fortran 2008 added the block construct, which allows you to define local scoping units within the block, but these are not supported in the syntax highlighting

For example:
<img width="315" alt="screen shot 2018-03-10 at 17 18 33" src="https://user-images.githubusercontent.com/3209794/37247293-1a11283a-2487-11e8-8cee-71aeee49d115.png">

**Comment by krvajal** [comment]
Fixed in #42
