### ISSUE TITLE
Using formatter findent with format code on save produces error "Failed to save" file

### ISSUE THREAD

**Issue by maroony** [krvajal/vscode-fortran-support#364]
**Describe the bug**
When using the formatter findent with option ```"editor.formatOnSave": true```, every time I got the following error message:

```
Failed to save 'file.f90': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.
```

I do not get this error when using formatter fprettify which is very slow in compare to findent.

**To Reproduce**

1. Open ```file.f90```
2. Make a change in this file
3. Hit key command for saving the file (e. g. Ctrl + S)
4. Get the error message

**Expected behavior**
Saved formatted file. 

**Build info (please complete the following information):**

- Linux x64 (Remote Development)
- Extension Version 2.6.2
- Visual Studio Code Version 1.63.2

**Additional context**

**Comment by gnikit** [comment]
Yeah, we have not implemented `formatOnSave` yet. I can't seem to remember why I didn't but the fix "should" be trivial, we only have overload an internal VS Code function with the existing one.

**Comment by trybik** [comment]
Bumping up this issue - at least some error-handling, as this is a very annoying and confusing error to get if you have `formatOnSave` globally enabled.

**Comment by gnikit** [comment]
Does setting up the formatter to "Disabled" for the extension solve the issue?

**Comment by trybik** [comment]
> Does setting up the formatter to "Disabled" for the extension solve the issue?

if you mean setting `"editor.formatOnSave": false`, then yes, it does prevent the error pop-up

**Comment by gnikit** [comment]
No, I mean the extension's settings for formatting: `  "fortran.formatting.formatter": "Disabled",`. If that does not stop it, for the time being you can setup workspace specific settings which take precedence over your global ones.

**Comment by HamGhibli** [comment]
Hi, I had similar issue today. 
So locally, in the folder's /.vscode/settings.json,     setting :  { "editor.formatOnSave": false }   solves the issue.
However, if we try locally the following settings enabling the formatOnSave while disabling fortran formatting,: 
{
    "editor.formatOnSave": true,
    "fortran.formatting.formatter": "Disabled"
}

the issue is still there !

as additional info, I am using:

- Ubuntu 20.04.3
- Vscode 1.63.2
- Modern Fortran Extension v2.6.2

**Comment by gnikit** [comment]
> enabling the formatOnSave while disabling fortran formatting,

Thanks @HamGhibli that's what I wanted to know. I am slightly short on time so any volunteers for this would be appreciated.

**Comment by swooping-magpie** [comment]
Hey guys I implemented a potential fix here: https://github.com/krvajal/vscode-fortran-support/pull/370. Please let me know how it is

**Comment by HamGhibli** [comment]
@gnikit thanks for the reply.  I did not switch to the pre-release version yet...

**Comment by gnikit** [comment]
I have issued a fix as a pre-release, I would **NOTE** the different interface that we have adopted in the extension.
