### ISSUE TITLE
forts missing warning disables fortls parsing if fortls is installed 

### ISSUE THREAD

**Issue by gnikit** [krvajal/vscode-fortran-support#365]
**Describe the bug**
Disabling the fortls prompt at the start of the extension and if fortls is installed will result to modern Fortran never registering the server.

**To Reproduce**
Set ignore warning.fortls to true

**Build info (please complete the following information):**

- OS: . Linux x64
- Extension Version 3.0.20220117 prerelease
- Visual Studio Code Version insiders 1.81

**Comment by stefabat** [comment]
I see, however even if I do not have fortls installed and the executable path is not manually set, clicking on the install prompt does nothing (I suppose because I do not have `pip` installed systemwise).

**Comment by gnikit** [comment]
Yeah, if you are missing pip the install will fail, silently possibly. If you want open a bug report on the modern Fortran and I'll get to it along with the other one.

I would also suggest, if you are still having trouble launching a language server within modern Fortran you open an issue for that too and we can go address it right now.

**Comment by stefabat** [comment]
> open a bug report on the modern Fortran
Isn't this repository the one of the Modern Fortran extension? The extension page on the MS marketplace brings me here.

**Comment by gnikit** [comment]
> > open a bug report on the modern Fortran
> 
> Isn't this repository the one of the Modern Fortran extension? The extension page on the MS marketplace brings me here.

Apologies, I got confused. I thought this was the fortran-language-server.

**Comment by gnikit** [comment]
BTW the temporary fix for this is to either delete from your settings or set to `  "fortran.ignoreWarning.fortls": false,`

**Comment by gnikit** [comment]
Available in the pre-release
