### ISSUE TITLE
Support for "select type" construct

### ISSUE THREAD

**Issue by kgerheiser** [krvajal/vscode-fortran-support#37]
The Fortran 2003 feature "select type" which allows you to find the type of a polymorphic entity is not supported through syntax highlighting like "select case" is.

<img width="321" alt="screen shot 2018-03-09 at 00 21 52" src="https://user-images.githubusercontent.com/3209794/37191809-e661ac4c-232f-11e8-9786-63b4f41280c0.png">

**Comment by krvajal** [comment]
Fixed in #42
