### ISSUE TITLE
Function definition not properly highlighted when preceeded by return type

### ISSUE THREAD

**Issue by kgerheiser** [krvajal/vscode-fortran-support#38]
Fortran allows you to specify the return type in the function definition, but that breaks syntax highlighting. Also, the "result" keyword is not properly highlighted.

<img width="422" alt="screen shot 2018-03-09 at 00 37 06" src="https://user-images.githubusercontent.com/3209794/37192187-099e5e6a-2332-11e8-9182-4cf76945264c.png">

**Comment by krvajal** [comment]
Fixed by #42
