### ISSUE TITLE
"abstract" keyword not highlighted

### ISSUE THREAD

**Issue by kgerheiser** [krvajal/vscode-fortran-support#39]
The abstract keyword, when applied to both interfaces and derived types, is not properly highlighted. 

<img width="211" alt="screen shot 2018-03-10 at 18 11 43" src="https://user-images.githubusercontent.com/3209794/37247758-81f75468-248e-11e8-902b-2c3b8514bd24.png">

<img width="318" alt="screen shot 2018-03-10 at 18 10 14" src="https://user-images.githubusercontent.com/3209794/37247752-5069cb2e-248e-11e8-98a1-7e62d7124a25.png">

**Comment by krvajal** [comment]
Fixed in #42
