### ISSUE TITLE
Execute formatter and pip failed on Windows

### ISSUE THREAD

**Issue by yhl1219** [krvajal/vscode-fortran-support#395]
I installed `fprettify` with pip3 and it's on my PATH, but when formatting the code, it failed with:

```
formatter exited with code: 3221225477
```

Also, when the extension tried to use `pip` to install `findent`, it also failed with this code.

## Re-produce

Extension version 2.6.2, python is 3.10, just change the formatter to `fprettify` and format my code, it would show this failure message

## Expected behavior

It should not fail

## Build Info

- OS: Windows 10
- Extension Version 2.6.2
- Visual Studio Code Version 1.65.0

## P.S.

I've tried to dig deep into the log, but I can't find any switch to explore more. If there's options, please do notify me and I would try to fix this

**Comment by gnikit** [comment]
Hi @yhl1219 thanks for the report, could you please try and switch to the pre-release version and tell me if that fixes the issue?

FYI the settings have slightly changed in v3.0.XXX (which is the Pre-Release) so you might want to have a loot that everything is setup correctly.

If that doesn't fix the issue could you try the following and post the results

1. run `fprettify` from the command line on a single file and see if that fails.
2. Post a copy of your Modern Fortran extension configuration settings i.e. things in your `.settings.json` that start with `"fortran."`

**Comment by yhl1219** [comment]
Well, it seems that in pre-release 3.0.2022021000, `fortls` cannot be started due to reason:

```
Error launching fortls: Please check that all selected options are supported by your language server version.
```

Also, I've checked running `fprettify` in my command line and it works just fine.

**Comment by yhl1219** [comment]
Also, I've tried to use my own Nodejs(16.13) to spawn a process and I got 3221225477 as the return code. It must be related to nodejs problem, I would check more.

**Comment by gnikit** [comment]
> Well, it seems that in pre-release 3.0.2022021000, `fortls` cannot be started due to reason:
> 
> ```
> Error launching fortls: Please check that all selected options are supported by your language server version.
> ```

That just means that you are passing erroneous options to `fortls`, but that shouldn't make a difference


> Also, I've checked running `fprettify` in my command line and it works just fine.

Okay that's good.

**Comment by gnikit** [comment]
> Also, I've tried to use my own Nodejs(16.13) to spawn a process and I got 3221225477 as the return code. It must be related to nodejs problem, I would check more.

I suspect that there some issue with permissions or access violation in your filesystem. Do you have read/write permissions of the folder and file you are trying to format?

**Comment by yhl1219** [comment]
I've found it, while using `spawnSync` in Nodejs, add option `{ shell: true }` would solve the problem. I don't know why it triggers access violation (that weird code) under Windows when there's no `shell: true`. Not sure whether it works under other OS

**Comment by yhl1219** [comment]
> I've found it, while using `spawnSync` in Nodejs, add option `{ shell: true }` would solve the problem. I don't know why it triggers access violation (that weird code) under Windows when there's no `shell: true`. Not sure whether it works under other OS

https://github.com/angular/angular-cli/issues/16119

Here, I've found some related problem. Option is to use `cmd.exe` or just add this `shell` option

**Comment by gnikit** [comment]
Here is the bit of code that is actually causing this https://github.com/nodejs/node/blob/842e5a10ac59c826f875ef79e92d144e2655cc9a/test/common.js#L502-L505 . 

As I mentioned this is the error in Windows for access violations. Something is blocking the spawning of processes, either lack of execute permissions, possibly lack of write permissions or even your antivirus software.

I spend some time a while back looking into the correct way to run subprocess in Modern Fortran and from what I vaguely recall we cannot use shell: true or run from any shell because variables that are defined in the shell configuration would take precedence over variables passed in our tools e.g. findent

**Comment by yhl1219** [comment]
Then I believe using cmd.exe to start in Windows should be the better choice

**Comment by gnikit** [comment]
> Then I believe using cmd.exe to start in Windows should be the better choice

See my previous reply as to why that is not possible. We cannot have global settings loaded when a shell is initialised override and/or be set when we launch our tools

**Comment by yhl1219** [comment]
Yeah I know, but it seems it is the only solution to execute it on Windows. Otherwise it would be directly aborted. I would check other extensions that utilize LSP to see what they are doing.

**Comment by gnikit** [comment]
I am still not convinced that this should be occurring in Windows. Please post all the output from `Help>About` in VS Code and also disable any antivirus software you have, restart VS Code and try and format a document then. (remember to re-enable your antivirus)

**Comment by gnikit** [comment]
> the only solution to execute it on Windows. 

That is not the norm, the extension works normally under Windows for all other users.

**Comment by gnikit** [comment]
I will spin-up a VM to verify but I doubt I will be able to reproduce the issue.

**Comment by yhl1219** [comment]
Ah ha, just modify `fortls` to `fortls.exe` under Windows, everything solved, I got this idea from `Omnisharp-vscode`

**Comment by gnikit** [comment]
> Ah ha, just modify `fortls` to `fortls.exe` under Windows, everything solved, I got this idea from `Omnisharp-vscode`

Yes that you are correct in that, maybe I should add it in the docs, but basically Windows needs the .exe extension. We had trouble spawning formatters in the past because of this.

A good solution might actually be to have the default name in Windows include the .exe and if the user chooses to edit the default path it is then up to them to include the extension.

So does that mean that your issue is solved?

FYI I span up my VM and all worked fine for me

**Comment by yhl1219** [comment]
```
const dotnet = this.platformInfo.isWindows() ? 'dotnet.exe' : 'dotnet';
```

This is how it is done in `Omnisharp-vscode`, you could directly use `process.platform === "win32"` to decide whether we should add this `.exe` extension name

**Comment by yhl1219** [comment]
It works fine after I change fortls to fortls.exe. Meanwhile, it seems that fprettify got stucked with the pre-release version. Probably with stdin problem? But I've tried in the command line and it's correct. Probably could pass the filename inside out using stdin to format the document. Anyway, findent works and it's OK now, I would close the issue.
