### ISSUE TITLE
GoToFunction needed

### ISSUE THREAD

**Issue by krvajal** [krvajal/vscode-fortran-support#4]
I really really want to have the ability to navigate to the declaration of a function by Cmd+Click in any statement including that function call. Wanna anyone to work on that?

**Comment by Poolshark** [comment]
That would be amazing! Unfortunately, I don't have enough knowledge and time to do it myself. Sorry!

**Comment by krvajal** [comment]
@Poolshark  we an walk through it together if you have the time

**Comment by pedro-ricardo** [comment]
The way i see it, you don't need to develop this feature inside this extension. There are some like **ctagsx** that uses Ctags features to navegate through the declarations/functions/subroutines. I'm correnty using it and can easily navegate through my fortran code.

**Comment by krvajal** [comment]
Can you post the link to the extension you are using?

**Comment by pedro-ricardo** [comment]
Sure.
It is called **Ctagsx**
https://marketplace.visualstudio.com/items?itemName=jtanx.ctagsx

**Comment by krvajal** [comment]
I have a working implementation of this. Will release soon.

**Comment by krvajal** [comment]
![preview](https://media.giphy.com/media/xUNda7JdFl6OeIrahi/giphy.gif)

**Comment by krvajal** [comment]
@pedro-ricardo this implementation does not depend on `ctags` and you don't have to generate the `tags` file either. Maybe the performance is a bit slower but is acceptable to me instead of having to relay on a third party binary.
Is this the kind of user experience you get with `ctags`. If not, I would like to know what features are missing.

**Comment by pedro-ricardo** [comment]
It's very close the `ctags` experience and i think it's a valid feature to the extension, the only thing that it seems to be missing is the `go back` macro, very important when navigating through different files.
Does your implementation work when the `subroutine`/`function` is in a **different module**, in a **different file** and within a **different folder**? How does it work in this case?
The `tags` file is there to deal with this kind of problem.

Even if it works only in the same file or folder, I think it is a very good feature to add and keep without dependencies on a third party binary, if the users needs some advanced navigation they should look for other programs like `ctags`.

But I also fear some incompatibilities when using both, could you include another flag for that (true by default of course, so new programmers don't miss this feature).

**Comment by alexandresardinha** [comment]
@krvajal , do you still want help on this?
I'm new on VS Code and I've never developed an extension for it, but I`m willing to learning it.

**Comment by krvajal** [comment]
The feature is already implemented but I need to test it a little bit more
before including it. If you want to help adding a few tests would be nice.
You should be able to code in TypeScript by that matter.

-- 
Miguel Carvajal

**Comment by krvajal** [comment]
@pedro-ricardo  according to the vscode keyboard shorcuts documentation page the so called `go back macro` can be triggered by `Ctrl+Alt+-` ([link here](https://code.visualstudio.com/docs/getstarted/keybindings)). So the feature is not missing.
Regarding the question about multiple files, it does works will multiple files if they are in the same project/workspace but at the time you need to have opened them at least once  to be parsed. 
I am looking for a way to parse the files when the project gets loaded without having a big performance penalty. If anyone knows a good approach to do that I am listening.

**Comment by alexandresardinha** [comment]
@krvajal Yes, I`d like to test it.
I`ve already forked vscode-fortran-support and learned how it works (as other vscode extensions).
As soon you commit this feature, let me know.
If you think it's good ideia to add some tests for other feature, feel free to suggest.

**Comment by krvajal** [comment]
@alexandresardinha I have created a pull request here #43. If you want to add some integration test and make sure the CI checks passes it would be great.

**Comment by krvajal** [comment]
The feature is now supported by the experimental language server introduced in version 2.0.0
