### ISSUE TITLE
"import" keyword not highlighted

### ISSUE THREAD

**Issue by kgerheiser** [krvajal/vscode-fortran-support#40]
The import keyword allows you to make host entities accessible in an interface block, but is not properly highlighted

<img width="328" alt="screen shot 2018-03-10 at 18 08 42" src="https://user-images.githubusercontent.com/3209794/37247784-e238445e-248e-11e8-90fc-1dea7dc0ddd9.png">

**Comment by pedro-ricardo** [comment]
I did it once, so maybe i can help you out with all the highlighting stuff. As most of your issues goes far beyond my knowledge of Fortran, I would like to suggest that you include in your issues an example of what color you want in the missing keyword. Like :

![example](https://user-images.githubusercontent.com/15893711/37247895-4b63f834-24a2-11e8-9709-e853cf07c2bd.png)

@krvajal, can you join all the highlighting issues in only one? It will be usefull to have only one place to search and talk about those changes. Thanks... 
Let's make this extension even better!

**Comment by krvajal** [comment]
I will add a new label for all the issues related with highlighting of the code so they can be find easily.



Miguel Carvajal PhD
Mobile: +32 465 35 71 77
Email: miguel.carvajalrivero@uantwerpen.be
Address: CMT Groenenborgerlaan 171, BE-2020 Antwerpen

**Comment by pedro-ricardo** [comment]
Thank you!
@kgerheiser let me know as soon as you include the colors you want for the keywords.

**Comment by kgerheiser** [comment]
@pedro-ricardo 

I think I have the syntax stuff mostly figured out. I have derived types working properly, and I'll make a pull request(s) for my issues when I'm done.

**Comment by pedro-ricardo** [comment]
That's awesome, thanks for the contribution. If you can please include issue #24 in your modifications.

**Comment by krvajal** [comment]
Fixed in #42
