### ISSUE TITLE
Fortran preprocessor directives prevent code folding

### ISSUE THREAD

**Issue by dfousek** [krvajal/vscode-fortran-support#409]
Hi Miguel !
Congrats for your work. 

I have a feature request: Preprocessor directives (#define, $ifdef, $elseif, $endif,...) prevent correct code folding. 

In my opinion, the most important code folding is the one in the "program...end program", "subroutine....end subroutine" level and preprocessor directives should not be disturbing this.
Kind regards,
Dimitri

**Comment by gnikit** [comment]
Duplicate of #135
