### ISSUE TITLE
Symbol List missing on version 1.0.1

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#44]
Even in the most basic file the symbol list feature (Ctrl+O) is not working anymore.

**Comment by krvajal** [comment]
Will take a look as soon as I can. That's why it would be nice to have some tests in place so this won't happen again.

**Comment by pedro-ricardo** [comment]
Happens in every project =]

**Comment by krvajal** [comment]
I added a PR to fix this #47
