### ISSUE TITLE
Highlighting of module names

### ISSUE THREAD

**Issue by vkbo** [krvajal/vscode-fortran-support#51]
Would it be possible to add highlighting for the module and end module name such that it is the same as with the use command?
That would make it consistent with subroutine and call.

![image](https://user-images.githubusercontent.com/1619840/38870908-8851b6da-424f-11e8-9aa1-b00dc94e83db.png)

**Comment by pedro-ricardo** [comment]
You mean something like this?
![mod](https://user-images.githubusercontent.com/15893711/38873302-cb643e94-422b-11e8-90f6-285623917b86.png)
Instead of this...
![mod2](https://user-images.githubusercontent.com/15893711/38873293-c6e875ce-422b-11e8-823d-6c28b55f4277.png)

**Comment by vkbo** [comment]
Yes, that's exactly it.

**Comment by pedro-ricardo** [comment]
Added a Pull-Request #53 to fix this minor highlight issue. Will close the issue as soon as the fix is in master branch.
