### ISSUE TITLE
Linting is no longer visible

### ISSUE THREAD

**Issue by susa3** [krvajal/vscode-fortran-support#55]
I've been using the extension for a while and for some reason the linting stopped working.
The syntax highlight is working perfectly fine for me it's just that the errors are no longer underlined.

**Comment by krvajal** [comment]
I will take a look at this as soon as I can @susa3. 
I wonder if anyone else is experiencing the same problem.

**Comment by krvajal** [comment]
This was indeed a regression introduced in a previous release of the extension that should be solved now with #56
