### ISSUE TITLE
Nested loop doesn't align properly

### ISSUE THREAD

**Issue by deprak** [krvajal/vscode-fortran-support#57]
When I make a nested loop, the "end do" just can't align to the corresponding 'do'.
![screenshot from 2018-04-28 22-26-25](https://user-images.githubusercontent.com/36827603/39398127-87df1b38-4b33-11e8-9fd1-7e29f910343d.png)

**Comment by pedro-ricardo** [comment]
It might be a Regex rule issue, I'll take look at it ...

**Comment by pedro-ricardo** [comment]
Fixed on #53
