### ISSUE TITLE
Symbol list fails on Subroutine without brackets

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#61]
Despite being a valid syntax, the declarations of subroutines without arguments and brackets as shown in the picture below, aren't recognized as symbols.
![symbols](https://user-images.githubusercontent.com/15893711/39958252-d4981116-55d6-11e8-8f32-6e87f30865ea.png)

**Comment by krvajal** [comment]
Please check release `v1.2.0`. It should be working now
