### ISSUE TITLE
Else statement highlight

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#62]
If a comment is added immediately after the `else` keyword, the comment is not highlighted properly and next line is highlighted as invalid. Picture below illustrate the error.
![highlight](https://user-images.githubusercontent.com/15893711/39958310-abc9b68a-55d7-11e8-8179-9f0fa5aebe9d.png)

**Comment by krvajal** [comment]
@pedro-ricardo can you provide plain text snippet as well so I can debut the syntax and don't have to type everything again.

**Comment by krvajal** [comment]
Had you try the else statement alone?

**Comment by pedro-ricardo** [comment]
Yes, Without that comment in front, it works just fine.... I had some busy weeks but i'm planning to look into this today.

**Comment by pedro-ricardo** [comment]
Solved by #68
