### ISSUE TITLE
Symbol list fails for functions with multiple line arguments

### ISSUE THREAD

**Issue by pedro-ricardo** [krvajal/vscode-fortran-support#78]
Same fix applied in PR #72 for `subroutine` need to be done in `function` regex ...
Forgot that ...  :-1:

**Comment by pedro-ricardo** [comment]
This bug is old, was not created in v1.3.0, fix will come soon.

**Comment by pedro-ricardo** [comment]
Fixed by #79

**Comment by krvajal** [comment]
@pedro-ricardo can you update this issue and the remaining ones?
